In [1]:
import numpy as np
import pandas as pd

In [2]:
Fasta = pd.read_csv("mm10_Fasta_Non_Donor_Acceptor_Replace.csv")

In [3]:
Fasta

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,...,LastIntronLength,SecondToLastLength,Pre,PreSequence,SecondToLastExonSequence,LastIntronSequence,LastExonSequence,Truncation,Seq,Replace
0,Wscd2,chr5,+,113490446,113589725,113550934,113588145,9,"113490446,113550422,113558348,113560900,113570...","113490940,113551334,113558463,113561085,113570...",...,10329,201,86816,CACGCTGAACACCCATCAACAAAACTGTCCTTTGTTGGATTTCTTT...,GGTTCAAAGGTGAGCGGGACCACTGGCGAAGCGGGCGGACCATCTG...,GTGACAGGAGGGAGGGTCGTGGACAGTGTGAGGTGCGGGTAATCAG...,AGTGGCCCGAGTTCGTGAGGAACTATGCCCCGTGGTGGGCCACGCA...,GTGACAGGAGGGAGGGTCGTGGACAGTGTGAGGTGCGGGTAATCAG...,GGTTCAAAGCAGAGCGGGACCACTGGCGAAGCGGGCGGACCATCTG...,TTCCTCAGAAAGAAGACATCTGCAGAAGCCTGTTTGGAATAGAACA...
1,Kl,chr5,+,150952606,150993817,150952716,150991854,5,"150952606,150980609,150982502,150988392,150991...","150953541,150981120,150982771,150989494,150993...",...,2022,1102,35786,GATAATCATTGCTCGTGGGGCGGCGGGAGCGGGGGTGGGCACCGCG...,GTGGACACTACTCTCTCTCAGTTTACTGACCCGAATGTCTATCTGT...,GTGAGACCCCGCCCCCTCAATCCCGGAAATACATCAGAGCGTGTAT...,CCTACGTGTTGGACGACATCAACCTTTGTGGCTACTTTGCGTATTC...,GTGAGACCCCGCCCCCTCAATCCCGGAAATACATCAGAGCGTGTAT...,GTGGACACTACTCTCTCTCAGTTTACTGACCCGAATGTCTATCTGT...,AAGGGAGCCAGCTGTGGCCCTGACCTCCGAGGCTGGCAAAAACTGT...
2,Tmx3,chr18,+,90510153,90543267,90510322,90540196,16,"90510153,90511278,90514204,90517393,90519104,9...","90510377,90511333,90514244,90517517,90519150,9...",...,1371,69,28345,CTTCGCTGGGCTACCGGGATCCTGAAGGAGGCCGGCCTAccccgcc...,GCCCAAGGAGGTGATAGCATTTTTCAGAGATTGAAAAGAATAGTAT...,GTAAGTTCTGACAGTATCTTCAATAGCTGAAAAATTTGGGGTTTTC...,TCTATATTCAAGAGCTCTCCACTTATGGGCTGCTTTCTTTTCGGGC...,GTAAGTTCTGACAGTATCTTCAATAGCTGAAAAATTTGGGGTTTTC...,GCCCAAGGAGCAGATAGCATTTTTCAGAGATTGAAAAGAATAGTAT...,actggagagaaacaccatgactgtaaccaatgtggtaaagctttta...
3,Arhgap21,chr2,-,20847918,20967721,20848711,20967410,25,"20847918,20853037,20854934,20855353,20855580,2...","20850385,20853069,20855040,20855395,20855706,2...",...,2652,32,114652,GGAAGGCTCTCCGAAAGCTGATTTTTCTCTGGCCTCCGAGTAACAC...,ATTCAGCTACTAGTGACTCCGCAAAATCTAAG,GTAAGTTGTTCTATACAGCTGGAAAACACTTCGTGGTAGCTTTGGG...,GGCTCCTGGGGATCCGGGAAGGATCAGTATAGCAGGGAACTGCTTG...,GTAAGTTGTTCTATACAGCTGGAAAACACTTCGTGGTAGCTTTGGG...,ATTCAGCTACTAGTGACTCCGCAAAATCTAAGCAAAGTTGTTCTAT...,CCTGTGCAGGGCCTGGGCCTGTCCCAGCACCCCAGGATATAGGCCC...
4,Ccnj,chr19,+,40831278,40848572,40832019,40846098,6,"40831278,40831978,40836916,40844659,40845044,4...","40831442,40832088,40837127,40844959,40845204,4...",...,494,160,13766,GTACGGCGAGCCGCCTGCCGGTCCTTTAACAATGGGCGGCGCGAGC...,ATTATGCCTTTCTAAATTATGCACCTTCTTTAGTAGCTGCTGCGTG...,GTAAGCCTCTTTGCTCTTGCATTTATAATTTCTAGTTAGCATTTTC...,TGCTCACGATAACGACGTGAAAGAAGCAAACAAGCAGAGGGGACAG...,GTAAGCCTCTTTGCTCTTGCATTTATAATTTCTAGTTAGCATTTTC...,ATTATGCCTTTCTAAATTATGCACCTTCTTTAGTAGCTGCTGCGTG...,GAGCTCCTGGGAAATGGGACTTCAGACTCCCAAGCCCAGAGTGGCC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,Wnt4,chr4,+,137277488,137299726,137277679,137296779,5,"137277488,137289113,137295440,137295659,137296...","137277756,137289349,137295572,137295802,137299...",...,509,143,18171,GGCTCTGGGGCGGCGCTGACAGTCGGGTCCGCCGGGCAGCGGGCGC...,GCTTCCAGTGGTCAGGATGCTCGGACAACATCGCCTATGGCGTAGC...,GTAGAGTGGTACCAACCCCATCGACACTGGGGCAGGGCTGCACGGG...,GCCATCTTGACACACATGCGGGTGGAGTGCAAGTGTCACGGGGTGT...,GTAGAGTGGTACCAACCCCATCGACACTGGGGCAGGGCTGCACGGG...,GCTTCCAGTGGTCAGGATGCTCGGACAACATCGCCTATGGCGTAGC...,AGCGGGAGAAGACACGCGTCAGTTCGACAAGGCAGTAGCGGTGGTG...
2366,Inpp4a,chr1,+,37299890,37410736,37357918,37408259,26,"37299890,37357342,37357814,37358507,37364109,3...","37300118,37357404,37358024,37358552,37364228,3...",...,9206,155,98875,GCGGGGTTGTGCGCTGTGTTCTGAGAGAAGGCGGTGGCAGGATTCG...,GTCTGTCGCCGCCTTAACGGGGTCCGATTCACCAGCTGCAAGAGTG...,GTGAGTGAGGCTGCTGCCAGGCTGCATCTGCCCAGCCACTTGCTCT...,TGAGGGTTGTCGGCGAGAAAACACAATGAAGAATGTTGGAAGTCGC...,GTGAGTGAGGCTGCTGCCAGGCTGCATCTGCCCAGCCACTTGCTCT...,GTCTGTCGCCGCCTTAACGGGGTCCGATTCACCAGCTGCAAGAGTG...,TGAGGCCCAGGACATGGAGTTGTAGTAGAAAAGGCATCTGCTTTTC...
2367,Trps1,chr15,-,50654751,50889691,50660674,50846940,6,"50654751,50664686,50822104,50830828,50846013,5...","50661736,50664809,50822708,50831958,50846942,5...",...,2950,123,224882,TGCAAACAACAGAAGACGGTTCATGGCTCTGGCCGCCGCGCCACCA...,AGGCGAAGAGGATCTGGTGTTTTTTGTGCCAATTGCCTGACCACAA...,GTAAGAACTTATCCTAGCCCTTTAGGGGAAGCTTACACAGATGAGC...,ACTCCCAGGCCTTTAAACATCATTAAACAAAACAACGGCGAGCAGA...,GTAAGAACTTATCCTAGCCCTTTAGGGGAAGCTTACACAGATGAGC...,AGGCGAAGAGGATCTGGTGTTTTTTGTGCCAATTGCCTGACCACAA...,ATCAGCCATAATTCCACTCATATTATAAGTAAATATAGCTATTCTA...
2368,Scn7a,chr2,-,66673424,66784914,66675497,66757357,25,"66673424,66680074,66680863,66682704,66683266,6...","66676561,66680345,66680968,66682842,66683320,6...",...,3513,271,104569,ATCTGTCTGTAGGTGGTCTCTGGGTCTGTGGAGCTAGCCTGGTGGC...,AACAAATTCCAAGGCTTCCTTTTTGACCTAGTAACACACCGTGTCT...,GTAAGGTTGGCTCTTGTCATTTTTCTTTAGAATATTACTTCAGTCT...,GGCTGCTGCTACCCTTGACAATAGGACAATACTTTGTGCCTCCTTC...,GTAAGGTTGGCTCTTGTCATTTTTCTTTAGAATATTACTTCAGTCT...,AACAAATTCCAAGGCTTCCTTTTTGACCTAGTAACACACCGTGTCT...,CTGGCCCCCGACAGCTGGAGTGATCTGGACAGCCTGCTCAGCTGTG...
2369,Zfp946,chr17,+,22424258,22456689,22451122,22455838,7,"22424258,22428480,22444167,22446796,22451096,2...","22424429,22428565,22444291,22446893,22451152,2...",...,845,127,29193,GGAAAATTCACCATTCCCTTAGGTACTTAAGTGAACAACTTGTTCT...,GATCTGTTAAGATTCAAGGACGTGGCTGTGGAATTCTCACAGGAGG...,GTAAGAATACTCTTCATGTAAAATTCTTGATTCCTTCTTTGAATTT...,TTTTTTCAGAAAATGATCATATATGTTACAAATATAAGAATGTCTT...,GTAAGAATACTCTTCATGTAAAATTCTTGATTCCTTCTTTGAATTT...,GATCTGTTAAGATTCAAGGACGTGGCTGTGGAATTCTCACAGGAGG...,GCGTCTACACCAGCACCTCCCACTTCACCCAGTGGATCAAGAGACA...

### Enhancer

In [4]:
Enhancer = pd.read_csv("Mouse_Motif_Regression_LastExon.csv")

In [5]:
Enhancer

       Name     Slope  Intercept  Pvalue        R2
0     GGACT  0.117800  -0.014730     0.0  0.055643
1     GAACT  0.101502  -0.014394     0.0  0.046392
2     TGGAC  0.096929  -0.014776     0.0  0.038428
3     GGACA  0.082938  -0.014563     0.0  0.034612
4     AGACT  0.081404  -0.014772     0.0  0.029159
...     ...       ...        ...     ...       ...
1019  AGGTC -0.049309  -0.015207     0.0  0.003481
1020  CAGGT -0.050436  -0.015226     0.0  0.004501
1021  TAGGT -0.051298  -0.015193     0.0  0.002082
1022  TCGAC -0.052638  -0.015186     0.0  0.002278
1023  AGGTA -0.054098  -0.015178     0.0  0.003969

[1024 rows x 5 columns]

In [6]:
Enhancer = Enhancer.head(100)

In [7]:
Enhancer = Enhancer["Name"].to_list()

In [8]:
motif_dic = dict()
positions = range(0, 410)
posi_str = []
for element in positions:
    posi_str.append(str(element))
motif_dic = dict.fromkeys(posi_str, 0)

In [9]:
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=210:
        Seq = Fasta.loc[i,"LastIntronSequence"][0:100] + Fasta.loc[i,"LastIntronSequence"][-100:] + Fasta.loc[i,"LastExonSequence"][0:210]
        
    if Fasta.loc[i,"LastExonLength"]<210:        
        Seq = Fasta.loc[i,"LastIntronSequence"][0:100] + Fasta.loc[i,"LastIntronSequence"][-100:] + Fasta.loc[i,"LastExonSequence"]
        
    for j in range(0, len(Seq)-6, 1):
        string = Seq[j:j+5]
        if(string in Enhancer):
            motif_dic[str(j)]+=1

In [10]:
Position = pd.DataFrame({"Index":range(0, 410)})

In [11]:
Value=[]
for i in range(0,410,1):
    Value.append(int(motif_dic[str(i)]))
Position["Enhancer"]=Value

In [12]:
Position

     Index  Enhancer
0        0         0
1        1        98
2        2       240
3        3       186
4        4       147
..     ...       ...
405    405         0
406    406         0
407    407         0
408    408         0
409    409         0

[410 rows x 2 columns]

In [13]:
df = pd.DataFrame({"Index":range(0, 410)})
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=210:
        Seq = Fasta.loc[i,"Seq"][(Fasta.loc[i,"SecondToLastLength"]):(Fasta.loc[i,"SecondToLastLength"]+200)] + Fasta.loc[i,"Seq"][-(Fasta.loc[i,"LastExonLength"]):][0:210]
        
    if Fasta.loc[i,"LastExonLength"]<210:        
        Seq = Fasta.loc[i,"Seq"][(Fasta.loc[i,"SecondToLastLength"]):(Fasta.loc[i,"SecondToLastLength"]+200)] + Fasta.loc[i,"Seq"][-(Fasta.loc[i,"LastExonLength"]):]
        
    seq = Seq
    if len(seq) >= 410:
        lis = [1]*410
    if len(seq) < 410:
        lis = [1]*len(seq) + [0]*(410-len(seq))
        
    New = np.array(lis)
    New = pd.DataFrame({Fasta.loc[i,"name"]:New})
    df = pd.merge(df, New, left_index=True, right_index=True)

In [14]:
df.drop(["Index"], axis=1, inplace=True)
df = df.T

In [15]:
df.loc["col_sum"] = df.sum()
df = df.T

In [16]:
Number = df[["col_sum"]]

In [17]:
Number.columns = ["Number"]

In [18]:
Data = pd.concat([Position, Number], axis=1)

In [19]:
Data

     Index  Enhancer  Number
0        0         0    2370
1        1        98    2370
2        2       240    2370
3        3       186    2370
4        4       147    2370
..     ...       ...     ...
405    405         0    2317
406    406         0    2317
407    407         0    2317
408    408         0    2317
409    409         0    2316

[410 rows x 3 columns]

In [20]:
Data["Mean"] = Data["Enhancer"]/Data["Number"]

In [21]:
Data.to_csv("Mouse_Enhancer_LastExonStart.csv", index=0)

### Silencer

In [22]:
Silencer = pd.read_csv("Mouse_Motif_Regression_LastExon.csv")

In [23]:
Silencer = Silencer.tail(100)

In [24]:
Silencer = Silencer["Name"].to_list()

In [25]:
motif_dic = dict()
positions = range(0, 410)
posi_str = []
for element in positions:
    posi_str.append(str(element))
motif_dic = dict.fromkeys(posi_str, 0)

In [26]:
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=210:
        Seq = Fasta.loc[i,"LastIntronSequence"][0:100] + Fasta.loc[i,"LastIntronSequence"][-100:] + Fasta.loc[i,"LastExonSequence"][0:210]
        
    if Fasta.loc[i,"LastExonLength"]<210:        
        Seq = Fasta.loc[i,"LastIntronSequence"][0:100] + Fasta.loc[i,"LastIntronSequence"][-100:] + Fasta.loc[i,"LastExonSequence"]
        
    for j in range(0, len(Seq)-6, 1):
        string = Seq[j:j+5]
        if(string in Silencer):
            motif_dic[str(j)]+=1

In [27]:
Position = pd.DataFrame({"Index":range(0, 410)})

In [28]:
Value=[]
for i in range(0,410,1):
    Value.append(int(motif_dic[str(i)]))
Position["Silencer"]=Value

In [29]:
Position

     Index  Silencer
0        0      1478
1        1       435
2        2       283
3        3       428
4        4       360
..     ...       ...
405    405         0
406    406         0
407    407         0
408    408         0
409    409         0

[410 rows x 2 columns]

In [30]:
Data = pd.concat([Position, Number], axis=1)

In [31]:
Data

     Index  Silencer  Number
0        0      1478    2370
1        1       435    2370
2        2       283    2370
3        3       428    2370
4        4       360    2370
..     ...       ...     ...
405    405         0    2317
406    406         0    2317
407    407         0    2317
408    408         0    2317
409    409         0    2316

[410 rows x 3 columns]

In [32]:
Data["Mean"] = Data["Silencer"]/Data["Number"]

In [33]:
Data.to_csv("Mouse_Silencer_LastExonStart.csv", index=0)