## Grab sequence

In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = pd.read_csv("/home/morgenlefay/iM6A/Annotation/UniqmRNA_GENCODE_VM7com_mm10_RefSeqpriority.txt", sep="\t", header=None)

In [3]:
Data.drop([0,11,13,14,15], axis=1, inplace=True)

In [4]:
Data

,1,2,3,4,5,6,7,8,9,10,12
0,ENSMUST00000086465.5,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",Adora1
1,ENSMUST00000140295.6,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",Sntg1
2,ENSMUST00000151309.6,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",Adgrb3
3,ENSMUST00000027312.10,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",Prim2
4,ENSMUST00000114313.6,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",Cflar
...,...,...,...,...,...,...,...,...,...,...,...
22418,ENSMUST00000115964.2,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325...",Tmlhe
22419,ENSMUST00000051100.6,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,",Vamp7
22420,ENSMUST00000167421.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,",CAAA01165726.1
22421,ENSMUST00000076951.3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,",Spry3
22422,ENSMUST00000178569.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,",AC234645.1

In [5]:
Data[1] = Data[12]

In [6]:
Data.drop([12], axis=1, inplace=True)

In [7]:
Data

,1,2,3,4,5,6,7,8,9,10
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

In [8]:
Data.columns = ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]

In [9]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Select coding genes

In [10]:
idx = (Data["cdsStart"] != Data["cdsEnd"])

In [11]:
Data = Data.loc[idx, ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]]

In [12]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Keep standard chromosomes

In [13]:
Data = Data[:22357]

### exonCount > 2

In [14]:
Data = Data[Data.exonCount > 2]

In [15]:
Data = Data.reset_index(drop = True)

In [16]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
17709,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6..."
17710,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6..."
17711,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6..."
17712,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6..."
17713,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6..."

In [17]:
Data["LastExonStart"] = 0
Data["LastExonEnd"] = 0

In [18]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",0,0
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",0,0
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",0,0
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",0,0
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
17709,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",0,0
17710,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",0,0
17711,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",0,0
17712,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",0,0
17713,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",0,0

In [19]:
for i in range(len(Data)):
    if Data.loc[i, "strand"] == "+":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[-2]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[-2]
    elif Data.loc[i, "strand"] == "-":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[0]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[0]

In [20]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884
...,...,...,...,...,...,...,...,...,...,...,...,...
17709,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487
17710,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304
17711,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050
17712,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719
17713,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033

In [21]:
for i in range(len(Data)):
    if Data.loc[i, "strand"] == "+":
        Data.loc[i,("SecondToLastExonStart")] = Data.loc[i, "exonStarts"].split(",")[-3]
        Data.loc[i,("SecondToLastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[-3]
    elif Data.loc[i, "strand"] == "-":
        Data.loc[i,("SecondToLastExonStart")] = Data.loc[i, "exonStarts"].split(",")[1]
        Data.loc[i,("SecondToLastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[1]

In [22]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17709,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076
17710,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264
17711,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236
17712,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331
17713,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214

In [23]:
StopCodon = pd.read_csv("/home/morgenlefay/iM6A/Annotation/StopCodon.csv")

In [24]:
StopCodon

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,StopCodon
0,Lypla1,chr1,+,4807822,4846739,4807913,4845016,4844962,4846739,TGA
1,Gm37988,chr1,+,4807891,4886770,4807913,4832316,4886743,4886770,TGA
2,Tcea1,chr1,+,4857813,4897905,4857913,4896364,4896355,4897905,TGA
3,Atp6v1h,chr1,+,5083079,5162529,5084450,5162165,5162104,5162529,TGA
4,Oprk1,chr1,+,5588492,5606131,5589048,5602784,5602251,5606131,TGA
...,...,...,...,...,...,...,...,...,...,...
21626,Gm21764,chrY,-,18061269,18061812,18061269,18061812,18061269,18061812,TAG
21627,Gm21852,chrY,-,40651453,40651996,40651453,40651996,40651453,40651996,TAG
21628,Gm21797,chrY,-,40775222,40775765,40775222,40775765,40775222,40775765,TAG
21629,Gm29644,chrY,-,70271305,70303343,70301098,70301674,70271305,70271539,TAG
21630,Gm29423,chrY,-,70292584,70303287,70293440,70303173,70292584,70293452,TAG

In [25]:
StopCodon = StopCodon[["name","chrom","strand","txStart","txEnd"]]

In [26]:
Data = pd.merge(Data, StopCodon, how="inner", on=["name","chrom","strand","txStart","txEnd"])

In [27]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214

In [28]:
Group = pd.read_csv("/home/morgenlefay/iM6A/Annotation/Group.csv")

In [29]:
Group

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,LastExonStart,LastExonEnd,Group
0,Xkr4,chr1,-,3214481,3671498,3216021,3671348,3,3214481,3216968,2
1,Rp1,chr1,-,4290845,4409241,4292980,4409187,4,4290845,4293012,2
2,Sox17,chr1,-,4491389,4497354,4491715,4495155,4,4491389,4492668,2
3,Mrpl15,chr1,-,4773210,4785739,4776463,4785677,5,4773210,4776801,2
4,Lypla1,chr1,+,4807822,4846739,4807913,4845016,9,4844962,4846739,2
...,...,...,...,...,...,...,...,...,...,...,...
22352,Gm21996,chrY,-,89713423,89745532,89713627,89744111,10,89713423,89713657,2
22353,Gm20837,chrY,+,90401247,90433263,90402678,90433059,8,90433029,90433263,2
22354,Gm21860,chrY,-,90754512,90754821,90754512,90754821,1,90754512,90754821,1
22355,Erdr1,chrY,+,90785441,90816464,90785670,90816447,4,90816435,90816464,2
22356,Gm21748,chrY,-,90838868,90839177,90838868,90839177,1,90838868,90839177,1

In [30]:
Group = Group[Group["Group"] != 1]
Group = Group[["name","chrom","strand","txStart","txEnd","Group"]]
Data = pd.merge(Data, Group, how="inner", on=["name","chrom","strand","txStart","txEnd"])

In [31]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2

In [32]:
Data.to_csv("Temp/MultiExon.csv", index=0)

### Create Bed

In [33]:
Bed = Data.iloc[:, [1, 3, 4, 0, 7, 2]]

In [34]:
Bed.to_csv("Temp/MultiExon.bed", sep="\t", header=False, index=False)

In [35]:
!bedtools getfasta -s -bed Temp/MultiExon.bed -fi /home/morgenlefay/Reference/Fasta/mm10.fa -fo Temp/MultiExon.txt