In [1]:
from Bio import SeqIO
from Bio.Seq import Seq
import numpy as np
import pandas as pd
import random

In [2]:
meta=[]
sequence=[]

In [3]:
seq = ('Temp/MultiExon.txt')

In [4]:
for seq_record in SeqIO.parse(seq, "fasta"):
    meta.append(str(seq_record.id))
    sequence.append(str(seq_record.seq))

In [5]:
Fasta = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})

In [6]:
Fasta

,Meta,Sequence
0,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...
17577,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [7]:
Data = pd.read_csv("Temp/MultiExon.csv")

In [8]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",2
...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",2

In [9]:
Result = pd.merge(Data, Fasta, left_index=True, right_index=True, how='outer')

In [10]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group,Meta,Sequence
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",2,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",2,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",2,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",2,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",2,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",2,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",2,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",2,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",2,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [11]:
Result.drop(["Meta","Sequence"], axis=1, inplace=True)

In [12]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",2
...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",2

In [13]:
Data = Result

In [14]:
LongInternalExon = pd.read_csv("/home/morgenlefay/iM6A/Chapter2/Figure1/mm10_InternalExon.csv")

In [15]:
LongInternalExon

        chrom  exonStart    exonEnd           name strand  ExonLength  Start
0        chr7   89935726   89935964          l7Rn6      -         238    217
1        chr7   89923563   89923715          l7Rn6      -         152    455
2        chr7   89920072   89920191          l7Rn6      -         119    607
3        chr2  155045611  155045781              a      +         170    111
4        chr2  155047675  155047740              a      +          65    281
...       ...        ...        ...            ...    ...         ...    ...
163855  chr18   38258269   38258362  0610009O20Rik      +          93   1179
163856  chr18   38254279   38254368  0610009O20Rik      +          89    691
163857  chr12   85822087   85822248  0610007P14Rik      -         161     52
163858  chr12   85816315   85816434  0610007P14Rik      -         119    304
163859  chr12   85819478   85819569  0610007P14Rik      -          91    213

[163860 rows x 7 columns]

In [16]:
LongInternalExon = LongInternalExon.reset_index(drop = False)
LongInternalExon["index"] = LongInternalExon["index"].astype(str)
LongInternalExon["ID"] = "ID"+ LongInternalExon["index"]
LongInternalExon.drop(["index"], axis=1,inplace=True)

In [17]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
0,chr7,89935726,89935964,l7Rn6,-,238,217,ID0
1,chr7,89923563,89923715,l7Rn6,-,152,455,ID1
2,chr7,89920072,89920191,l7Rn6,-,119,607,ID2
3,chr2,155045611,155045781,a,+,170,111,ID3
4,chr2,155047675,155047740,a,+,65,281,ID4
...,...,...,...,...,...,...,...,...
163855,chr18,38258269,38258362,0610009O20Rik,+,93,1179,ID163855
163856,chr18,38254279,38254368,0610009O20Rik,+,89,691,ID163856
163857,chr12,85822087,85822248,0610007P14Rik,-,161,52,ID163857
163858,chr12,85816315,85816434,0610007P14Rik,-,119,304,ID163858
163859,chr12,85819478,85819569,0610007P14Rik,-,91,213,ID163859

In [18]:
# LongInternalExon = LongInternalExon[LongInternalExon["ExonLength"]>=200]
# LongInternalExon = LongInternalExon.reset_index(drop = True)

In [19]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
0,chr7,89935726,89935964,l7Rn6,-,238,217,ID0
1,chr7,89923563,89923715,l7Rn6,-,152,455,ID1
2,chr7,89920072,89920191,l7Rn6,-,119,607,ID2
3,chr2,155045611,155045781,a,+,170,111,ID3
4,chr2,155047675,155047740,a,+,65,281,ID4
...,...,...,...,...,...,...,...,...
163855,chr18,38258269,38258362,0610009O20Rik,+,93,1179,ID163855
163856,chr18,38254279,38254368,0610009O20Rik,+,89,691,ID163856
163857,chr12,85822087,85822248,0610007P14Rik,-,161,52,ID163857
163858,chr12,85816315,85816434,0610007P14Rik,-,119,304,ID163858
163859,chr12,85819478,85819569,0610007P14Rik,-,91,213,ID163859

In [20]:
M6A = pd.read_csv("/home/morgenlefay/iM6A/Chapter3/Figure1/iM6A_Mouse_IL.csv")

In [21]:
M6A

        chrom     Start       End     name strand        WT        IL
0        chr1   3214485   3214486     Xkr4      -  0.000000  0.000000
1        chr1   3214554   3214555     Xkr4      -  0.000000  0.000000
2        chr1   3214662   3214663     Xkr4      -  0.199716  0.199716
3        chr1   3214724   3214725     Xkr4      -  0.152102  0.152101
4        chr1   3214732   3214733     Xkr4      -  0.652838  0.652836
...       ...       ...       ...      ...    ...       ...       ...
1769220  chrY  10433185  10433186  Gm28510      +  0.000000  0.001592
1769221  chrY  51866751  51866752  Gm20920      +  0.000000  0.001402
1769222  chrY  64487901  64487902  Gm20908      +  0.000000  0.001402
1769223  chrY  74478146  74478147  Gm29110      +  0.000000  0.077403
1769224  chrY  75203467  75203468  Gm20814      +  0.000000  0.072174

[1769225 rows x 7 columns]

In [22]:
M6A.columns = ["chrom","m6AStart","m6AEnd","name","strand","WT","IL"]

In [23]:
Data = pd.merge(M6A, Data, how="inner", on=["chrom","name","strand"])

In [24]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group
0,chr1,3214485,3214486,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2
1,chr1,3214554,3214555,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2
2,chr1,3214662,3214663,Xkr4,-,0.199716,0.199716,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2
3,chr1,3214724,3214725,Xkr4,-,0.152102,0.152101,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2
4,chr1,3214732,3214733,Xkr4,-,0.652838,0.652836,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589988,chrY,90793403,90793404,Erdr1,+,0.232404,0.259672,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2
1589989,chrY,90793407,90793408,Erdr1,+,0.218156,0.176900,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2
1589990,chrY,90816374,90816375,Erdr1,+,0.000000,0.020307,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2
1589991,chrY,90816408,90816409,Erdr1,+,0.000000,0.003735,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2
1589992,chrY,90816418,90816419,Erdr1,+,0.000000,0.002582,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2

In [25]:
Data = pd.merge(Data, LongInternalExon, how="inner", on=["chrom","name","strand"])

In [26]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,3214485,3214486,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2,3421701,3421901,200,947,ID3950
1,chr1,3214554,3214555,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2,3421701,3421901,200,947,ID3950
2,chr1,3214662,3214663,Xkr4,-,0.199716,0.199716,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2,3421701,3421901,200,947,ID3950
3,chr1,3214724,3214725,Xkr4,-,0.152102,0.152101,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2,3421701,3421901,200,947,ID3950
4,chr1,3214732,3214733,Xkr4,-,0.652838,0.652836,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",2,3421701,3421901,200,947,ID3950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22368761,chrY,90816374,90816375,Erdr1,+,0.000000,0.020307,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2,90816348,90816433,85,660,ID113115
22368762,chrY,90816408,90816409,Erdr1,+,0.000000,0.003735,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2,90793295,90793417,122,538,ID113114
22368763,chrY,90816408,90816409,Erdr1,+,0.000000,0.003735,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2,90816348,90816433,85,660,ID113115
22368764,chrY,90816418,90816419,Erdr1,+,0.000000,0.002582,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2,90793295,90793417,122,538,ID113114
22368765,chrY,90816418,90816419,Erdr1,+,0.000000,0.002582,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",2,90816348,90816433,85,660,ID113115

In [27]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [28]:
Positive = Positive[(Positive["m6AStart"]>=Positive["exonStart"]) & (Positive["m6AEnd"]<=Positive["exonEnd"])]
Negative = Negative[(Negative["m6AStart"]>=Negative["exonStart"]) & (Negative["m6AEnd"]<=Negative["exonEnd"])]

In [29]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [30]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,Group,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127
1,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127
2,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127
3,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127
4,chr1,4832377,4832378,Lypla1,+,0.0,0.006360,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768032,chrY,89724896,89724897,Gm21996,-,0.0,0.039020,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89724833,89724900,67,278,ID101758
768033,chrY,89731959,89731960,Gm21996,-,0.0,0.070523,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89731936,89731971,35,243,ID101759
768034,chrY,89744025,89744026,Gm21996,-,0.0,0.012377,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753
768035,chrY,89744046,89744047,Gm21996,-,0.0,0.663240,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753
768036,chrY,89744124,89744125,Gm21996,-,0.0,0.000000,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753

In [31]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [32]:
Positive["m6APosition"] = Positive["m6AStart"] - Positive["exonStart"]
Negative["m6APosition"] = Negative["exonEnd"] - Negative["m6AEnd"]

In [33]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [34]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,exonCount,exonStarts,exonEnds,Group,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127,15
1,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127,15
2,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127,54
3,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127,54
4,chr1,4832377,4832378,Lypla1,+,0.0,0.006360,4807822,4846739,4807913,...,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",2,4832310,4832381,71,306,ID80127,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768032,chrY,89724896,89724897,Gm21996,-,0.0,0.039020,89713423,89745532,89713627,...,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89724833,89724900,67,278,ID101758,3
768033,chrY,89731959,89731960,Gm21996,-,0.0,0.070523,89713423,89745532,89713627,...,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89731936,89731971,35,243,ID101759,11
768034,chrY,89744025,89744026,Gm21996,-,0.0,0.012377,89713423,89745532,89713627,...,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753,99
768035,chrY,89744046,89744047,Gm21996,-,0.0,0.663240,89713423,89745532,89713627,...,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753,78
768036,chrY,89744124,89744125,Gm21996,-,0.0,0.000000,89713423,89745532,89713627,...,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",2,89743993,89744125,132,44,ID101753,0

In [35]:
Data.to_csv("iM6A_Mouse_IL_Start.csv", index=0)

In [37]:
Data = Data[Data["ExonLength"]>=200]

In [38]:
Data = Data.sort_values(by=["ID","m6APosition"], axis=0, ascending=[True,True])
Data = Data.reset_index(drop = True)

In [39]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,exonStarts,exonEnds,Group,GeneLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr7,89935957,89935958,l7Rn6,-,0.000000,0.005398,89917528,89941185,89918952,...,"89917528,89920072,89923563,89935726,89940968,","89919007,89920191,89923715,89935964,89941185,",2,23657,89935726,89935964,238,217,ID0,6
1,chr7,89935917,89935918,l7Rn6,-,0.000000,0.056951,89917528,89941185,89918952,...,"89917528,89920072,89923563,89935726,89940968,","89919007,89920191,89923715,89935964,89941185,",2,23657,89935726,89935964,238,217,ID0,46
2,chr7,89935893,89935894,l7Rn6,-,0.000000,0.008117,89917528,89941185,89918952,...,"89917528,89920072,89923563,89935726,89940968,","89919007,89920191,89923715,89935964,89941185,",2,23657,89935726,89935964,238,217,ID0,70
3,chr7,89935867,89935868,l7Rn6,-,0.000000,0.018465,89917528,89941185,89918952,...,"89917528,89920072,89923563,89935726,89940968,","89919007,89920191,89923715,89935964,89941185,",2,23657,89935726,89935964,238,217,ID0,96
4,chr11,109365589,109365590,Gna13,+,0.000000,0.025764,109362830,109401369,109362973,...,"109362830,109365535,109392345,109395913,","109363256,109365762,109392396,109401369,",2,38539,109365535,109365762,227,426,ID100014,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259217,chr9,107615677,107615678,Gnai2,-,0.322802,0.812709,107614124,107635367,107615634,...,"107614124,107615611,107616154,107616413,107616...","107615098,107615825,107616308,107616543,107617...",3,21243,107615611,107615825,214,1027,ID99991,147
259218,chr9,107615662,107615663,Gnai2,-,0.179099,0.587262,107614124,107635367,107615634,...,"107614124,107615611,107616154,107616413,107616...","107615098,107615825,107616308,107616543,107617...",3,21243,107615611,107615825,214,1027,ID99991,162
259219,chr9,107615659,107615660,Gnai2,-,0.084676,0.385677,107614124,107635367,107615634,...,"107614124,107615611,107616154,107616413,107616...","107615098,107615825,107616308,107616543,107617...",3,21243,107615611,107615825,214,1027,ID99991,165
259220,chr9,107615650,107615651,Gnai2,-,0.227262,0.631648,107614124,107635367,107615634,...,"107614124,107615611,107616154,107616413,107616...","107615098,107615825,107616308,107616543,107617...",3,21243,107615611,107615825,214,1027,ID99991,174
259221,chr9,107615623,107615624,Gnai2,-,0.089047,0.462114,107614124,107635367,107615634,...,"107614124,107615611,107616154,107616413,107616...","107615098,107615825,107616308,107616543,107617...",3,21243,107615611,107615825,214,1027,ID99991,201

In [39]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr7,89935957,89935958,l7Rn6,-,0.000000,0.005398,89917528,89941185,89918952,...,89920191,2,23657,1479,89935726,89935964,238,217,ID0,6
1,chr7,89935917,89935918,l7Rn6,-,0.000000,0.056951,89917528,89941185,89918952,...,89920191,2,23657,1479,89935726,89935964,238,217,ID0,46
2,chr7,89935893,89935894,l7Rn6,-,0.000000,0.008117,89917528,89941185,89918952,...,89920191,2,23657,1479,89935726,89935964,238,217,ID0,70
3,chr7,89935867,89935868,l7Rn6,-,0.000000,0.018465,89917528,89941185,89918952,...,89920191,2,23657,1479,89935726,89935964,238,217,ID0,96
4,chr11,109365589,109365590,Gna13,+,0.000000,0.025764,109362830,109401369,109362973,...,109392396,2,38539,5456,109365535,109365762,227,426,ID100014,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259217,chr9,107615677,107615678,Gnai2,-,0.322802,0.812709,107614124,107635367,107615634,...,107615825,3,21243,974,107615611,107615825,214,1027,ID99991,147
259218,chr9,107615662,107615663,Gnai2,-,0.179099,0.587262,107614124,107635367,107615634,...,107615825,3,21243,974,107615611,107615825,214,1027,ID99991,162
259219,chr9,107615659,107615660,Gnai2,-,0.084676,0.385677,107614124,107635367,107615634,...,107615825,3,21243,974,107615611,107615825,214,1027,ID99991,165
259220,chr9,107615650,107615651,Gnai2,-,0.227262,0.631648,107614124,107635367,107615634,...,107615825,3,21243,974,107615611,107615825,214,1027,ID99991,174
259221,chr9,107615623,107615624,Gnai2,-,0.089047,0.462114,107614124,107635367,107615634,...,107615825,3,21243,974,107615611,107615825,214,1027,ID99991,201

In [40]:
Data["Probabilty"] = Data["IL"] - Data["WT"]

### Heatmap

In [41]:
ID = Data["ID"].to_list()
ID = list(set(ID))

In [42]:
Heatmap = pd.DataFrame({"Index":range(0, 200, 5)})

In [43]:
for i in range(len(ID)):
    df = Data[Data["ID"]==ID[i]]
    df = df.reset_index(drop = True)
    
    Position = df["m6APosition"].to_list()
    Prob = df["Probabilty"].to_list()
    Dict = dict(zip(Position,Prob))
    
    
    Value = []
    for j in range(40):
        Interval = [k for k in range(j*5,(j+1)*5,1)]
        
        List = []
        for num in Interval:
            if num in Dict.keys():
                List.append(Dict[num])
            if num not in Dict.keys():
                List.append(0)
        Max = max(List)
        Min = min(List)
        
        if abs(Max) >= abs(Min):
            Value.append(Max)
        if abs(Max) < abs(Min):
            Value.append(Min)
    
    df = pd.DataFrame({ID[i]:Value})
    Heatmap = pd.merge(Heatmap, df, left_index=True, right_index=True, how='outer')

In [44]:
Heatmap

,Index,ID510,ID30139,ID5691,ID52081,ID79153,ID74239,ID84643,ID148854,ID7187,...,ID80977,ID35701,ID144356,ID89808,ID55257,ID58145,ID129993,ID84700,ID98513,ID60416
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.216188,0.000000,0.000000,0.000000,0.000000,0.070140
1,5,0.000000,0.000000,0.000000,0.009102,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.053157
2,10,0.035465,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.052672
3,15,0.000000,0.000000,0.000000,0.002550,0.000000,0.000000,0.046153,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.486316,0.000000,0.000000,0.000000,0.000000,0.000000,0.030771
4,20,0.000000,0.000000,0.066910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.095326,0.000000,0.000000,0.018787,0.000000,0.000000
5,25,0.049022,0.001745,0.000000,0.000000,0.002276,0.000000,0.000000,0.000000,0.000000,...,0.001794,0.000000,0.000000,0.024867,0.000000,0.000000,0.000000,0.000000,0.607090,0.000000
6,30,0.000000,0.000000,0.000000,0.000000,0.002149,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.302452,0.000000,0.749656,0.000000
7,35,0.000000,0.000000,0.000000,0.000000,0.000000,0.133321,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.340516,0.000000,0.387716,0.021396,0.000000,0.000000
8,40,0.000000,-0.000545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.042533
9,45,0.000000,0.000000,0.000000,0.000000,0.000000,0.102943,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.009786,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.002999,0.000000,0.000000,0.000000,0.000000,0.000000
11,55,0.000000,0.000000,0.000000,0.000000,0.000000,0.160571,0.000000,0.044268,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.059752,0.163196,0.000000,0.000000,0.000000
12,60,0.000000,0.000000,0.038837,0.000000,0.000000,0.000000,0.414684,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.116182,0.121569,0.000000
13,65,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.002513,0.001668,0.000000,0.005426,0.000000,0.000000,0.017014
14,70,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.029721,0.047798,0.000000
15,75,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.420486,0.000000,0.011278,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,80,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.168803,0.000000,0.000000,0.000000,0.000000,0.000000,0.011386,0.000000,0.000000
17,85,0.000000,0.000000,0.000000,0.001752,0.000000,0.190985,0.022386,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.014967,0.000000,0.006244,0.000000,0.035999
18,90,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.276290,0.000000,0.000000,0.000000,0.000000,0.006192,0.000000,0.000000
19,95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.091671,0.000000,0.000000,0.000000,0.000000,0.000000,0.010892,0.000000,0.000000,0.000000
20,100,0.000000,0.000000,0.000000,0.000237,0.000000,0.000000,0.000000,0.000000,0.001061,...,0.000000,0.000000,0.069818,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,105,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.025700,0.016161,0.000000,0.000000,0.000000,0.000000,0.000000
22,110,0.000000,0.000000,0.128063,0.000000,0.000000,0.000000,0.000000,0.002933,0.000000,...,0.025041,0.000000,0.162733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,115,0.000000,-0.260078,0.000000,0.000000,0.000000,0.003033,0.044023,0.000000,0.000000,...,0.000000,0.286527,0.000000,0.000000,0.000000,0.000000,0.003072,0.082021,0.069967,0.000000
24,120,0.000000,-0.329287,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,125,0.000000,0.000000,0.007135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.085575,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,130,0.000000,-0.209712,0.000000,0.000000,0.000000,0.000000,0.000000,0.000524,0.000000,...,0.007629,0.000000,0.000000,0.000000,0.000000,0.010560,0.000000,0.000000,0.000000,0.000000
27,135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.203158,0.000000,0.000000,0.000000,0.167212,0.000000,0.089045
28,140,0.029177,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.272955,0.000000,0.000000,0.030432,0.000000,0.002290,0.000000,0.000000,0.000000
29,145,0.000000,-0.056520,0.000000,0.000000,0.013396,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.103301,0.000000,0.000000,0.000000,0.000000,0.000000,0.235394
30,150,0.148622,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.352439,0.000000,0.000000
31,155,0.000000,-0.025924,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001673,0.000000,0.000000,0.055369,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,160,0.000000,0.000000,0.000000,0.000000,0.000000,0.002575,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.103312,0.000000,0.000000,0.000000,0.001834,0.000000,0.000000,0.000000
33,165,0.194559,-0.051961,0.000000,0.000000,0.000000,0.005189,0.000000,0.000000,0.099365,...,0.000000,0.000000,0.000000,0.167856,0.000000,0.000000,0.000000,0.320782,0.000000,0.000000
34,170,0.000000,0.000000,0.000000,0.000000,0.002487,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.128871,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396817
35,175,0.021306,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.004413,0.000000,0.000000,0.059294,0.000000,0.000000,0.000000,0.000000,0.000000
36,180,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.259200,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.149759,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,190,0.000000,0.000000,0.000000,-0.023170,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.123537,0.000000,0.000000
39,195,0.011433,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.192096,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.085868,0.000000,0.013404,0.344205

In [45]:
Heatmap.to_csv("Heatmap/mm10_Heatmap_LongInternalExonStart_200.csv", index=0)