In [1]:
from Bio import SeqIO
from Bio.Seq import Seq
import numpy as np
import pandas as pd
import random

In [2]:
meta=[]
sequence=[]

In [3]:
seq = ('Temp/MultiExon.txt')

In [4]:
for seq_record in SeqIO.parse(seq, "fasta"):
    meta.append(str(seq_record.id))
    sequence.append(str(seq_record.seq))

In [5]:
Fasta = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})

In [6]:
Fasta

,Meta,Sequence
0,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...
17577,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [7]:
Data = pd.read_csv("Temp/MultiExon.csv")

In [8]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2

In [9]:
Result = pd.merge(Data, Fasta, left_index=True, right_index=True, how='outer')

In [10]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,Meta,Sequence
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [11]:
Result.drop(["Meta","Sequence"], axis=1, inplace=True)

In [12]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2

In [13]:
Result["GeneLength"] = Result["txEnd"] - Result["txStart"]
Result["LastExonLength"] = Result["LastExonEnd"] - Result["LastExonStart"]

In [14]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2,36207,4366
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2,937764,2159
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2,762158,807
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2,215986,495
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2,47325,5101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2,28112,902
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2,29578,1189
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2,22732,303
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2,10506,669
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2,4017,632

In [15]:
Data = Result

In [16]:
LongInternalExon = pd.read_csv("/home/morgenlefay/iM6A/Chapter2/Figure1/mm10_InternalExon.csv")

In [17]:
LongInternalExon

        chrom  exonStart    exonEnd           name strand  ExonLength  Start
0        chr7   89935726   89935964          l7Rn6      -         238    217
1        chr7   89923563   89923715          l7Rn6      -         152    455
2        chr7   89920072   89920191          l7Rn6      -         119    607
3        chr2  155045611  155045781              a      +         170    111
4        chr2  155047675  155047740              a      +          65    281
...       ...        ...        ...            ...    ...         ...    ...
163855  chr18   38258269   38258362  0610009O20Rik      +          93   1179
163856  chr18   38254279   38254368  0610009O20Rik      +          89    691
163857  chr12   85822087   85822248  0610007P14Rik      -         161     52
163858  chr12   85816315   85816434  0610007P14Rik      -         119    304
163859  chr12   85819478   85819569  0610007P14Rik      -          91    213

[163860 rows x 7 columns]

In [18]:
LongInternalExon = LongInternalExon.reset_index(drop = False)
LongInternalExon["index"] = LongInternalExon["index"].astype(str)
LongInternalExon["ID"] = "ID"+ LongInternalExon["index"]
LongInternalExon.drop(["index"], axis=1,inplace=True)

In [19]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
0,chr7,89935726,89935964,l7Rn6,-,238,217,ID0
1,chr7,89923563,89923715,l7Rn6,-,152,455,ID1
2,chr7,89920072,89920191,l7Rn6,-,119,607,ID2
3,chr2,155045611,155045781,a,+,170,111,ID3
4,chr2,155047675,155047740,a,+,65,281,ID4
...,...,...,...,...,...,...,...,...
163855,chr18,38258269,38258362,0610009O20Rik,+,93,1179,ID163855
163856,chr18,38254279,38254368,0610009O20Rik,+,89,691,ID163856
163857,chr12,85822087,85822248,0610007P14Rik,-,161,52,ID163857
163858,chr12,85816315,85816434,0610007P14Rik,-,119,304,ID163858
163859,chr12,85819478,85819569,0610007P14Rik,-,91,213,ID163859

In [20]:
LongInternalExon = LongInternalExon.iloc[120000:]

In [21]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
120000,chr9,54708382,54708487,Dnaja4,+,105,483,ID120000
120001,chr9,54714269,54714370,Dnaja4,+,101,1047,ID120001
120002,chr16,4693211,4693412,Dnaja3,+,201,493,ID120002
120003,chr16,4694363,4694516,Dnaja3,+,153,694,ID120003
120004,chr16,4696388,4696536,Dnaja3,+,148,847,ID120004
...,...,...,...,...,...,...,...,...
163855,chr18,38258269,38258362,0610009O20Rik,+,93,1179,ID163855
163856,chr18,38254279,38254368,0610009O20Rik,+,89,691,ID163856
163857,chr12,85822087,85822248,0610007P14Rik,-,161,52,ID163857
163858,chr12,85816315,85816434,0610007P14Rik,-,119,304,ID163858
163859,chr12,85819478,85819569,0610007P14Rik,-,91,213,ID163859

In [22]:
M6A = pd.read_csv("/home/morgenlefay/iM6A/Chapter3/Figure1/iM6A_Mouse_IL.csv")

In [23]:
M6A

        chrom     Start       End     name strand        WT        IL
0        chr1   3214485   3214486     Xkr4      -  0.000000  0.000000
1        chr1   3214554   3214555     Xkr4      -  0.000000  0.000000
2        chr1   3214662   3214663     Xkr4      -  0.199716  0.199716
3        chr1   3214724   3214725     Xkr4      -  0.152102  0.152101
4        chr1   3214732   3214733     Xkr4      -  0.652838  0.652836
...       ...       ...       ...      ...    ...       ...       ...
1769220  chrY  10433185  10433186  Gm28510      +  0.000000  0.001592
1769221  chrY  51866751  51866752  Gm20920      +  0.000000  0.001402
1769222  chrY  64487901  64487902  Gm20908      +  0.000000  0.001402
1769223  chrY  74478146  74478147  Gm29110      +  0.000000  0.077403
1769224  chrY  75203467  75203468  Gm20814      +  0.000000  0.072174

[1769225 rows x 7 columns]

In [24]:
M6A.columns = ["chrom","m6AStart","m6AEnd","name","strand","WT","IL"]

In [25]:
Data = pd.merge(M6A, Data, how="inner", on=["chrom","name","strand"])

In [26]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength
0,chr1,3214485,3214486,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
1,chr1,3214554,3214555,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
2,chr1,3214662,3214663,Xkr4,-,0.199716,0.199716,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
3,chr1,3214724,3214725,Xkr4,-,0.152102,0.152101,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
4,chr1,3214732,3214733,Xkr4,-,0.652838,0.652836,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589988,chrY,90793403,90793404,Erdr1,+,0.232404,0.259672,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589989,chrY,90793407,90793408,Erdr1,+,0.218156,0.176900,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589990,chrY,90816374,90816375,Erdr1,+,0.000000,0.020307,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589991,chrY,90816408,90816409,Erdr1,+,0.000000,0.003735,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589992,chrY,90816418,90816419,Erdr1,+,0.000000,0.002582,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29

In [27]:
Data = pd.merge(Data, LongInternalExon, how="inner", on=["chrom","name","strand"])

In [28]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,5083112,5083113,Atp6v1h,+,0.0,0.0,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5124276,5124469,193,910,ID147076
1,chr1,5083112,5083113,Atp6v1h,+,0.0,0.0,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5133083,5133262,179,1103,ID147077
2,chr1,5083112,5083113,Atp6v1h,+,0.0,0.0,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
3,chr1,5083112,5083113,Atp6v1h,+,0.0,0.0,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5135811,5135937,126,1282,ID147079
4,chr1,5083112,5083113,Atp6v1h,+,0.0,0.0,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5095614,5095728,114,539,ID147080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5979368,chrY,61134254,61134255,1700040F15Rik,+,0.0,0.0,61102246,61134259,61103668,...,61133568,61133667,2,32013,234,61133568,61133667,99,598,ID163359
5979369,chrY,61134254,61134255,1700040F15Rik,+,0.0,0.0,61102246,61134259,61103668,...,61133568,61133667,2,32013,234,61115110,61115177,67,176,ID163360
5979370,chrY,61134254,61134255,1700040F15Rik,+,0.0,0.0,61102246,61134259,61103668,...,61133568,61133667,2,32013,234,61122792,61122859,67,278,ID163361
5979371,chrY,61134254,61134255,1700040F15Rik,+,0.0,0.0,61102246,61134259,61103668,...,61133568,61133667,2,32013,234,61115727,61115762,35,243,ID163362
5979372,chrY,61134254,61134255,1700040F15Rik,+,0.0,0.0,61102246,61134259,61103668,...,61133568,61133667,2,32013,234,61123418,61123453,35,345,ID163363

In [29]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [30]:
Positive = Positive[(Positive["m6AStart"]>=Positive["exonStart"]) & (Positive["m6AEnd"]<=Positive["exonEnd"])]
Negative = Negative[(Negative["m6AStart"]>=Negative["exonStart"]) & (Negative["m6AEnd"]<=Negative["exonEnd"])]

In [31]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [32]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,5084427,5084428,Atp6v1h,+,0.000000,0.077187,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
1,chr1,5084453,5084454,Atp6v1h,+,0.000000,0.063405,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
2,chr1,5084463,5084464,Atp6v1h,+,0.002439,0.250139,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
3,chr1,5084495,5084496,Atp6v1h,+,0.000000,0.008835,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
4,chr1,5084499,5084500,Atp6v1h,+,0.000000,0.045467,5083079,5162529,5084450,...,5149947,5150061,2,79450,425,5084416,5084563,147,199,ID147078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199754,chrY,1280423,1280424,Ddx3y,-,0.000000,0.382121,1260770,1286629,1263287,...,1263569,1263700,2,25859,2597,1280309,1280439,130,260,ID123592
199755,chrY,1282909,1282910,Ddx3y,-,0.000000,0.155704,1260770,1286629,1263287,...,1263569,1263700,2,25859,2597,1282900,1282948,48,212,ID123598
199756,chrY,1282917,1282918,Ddx3y,-,0.000000,0.189674,1260770,1286629,1263287,...,1263569,1263700,2,25859,2597,1282900,1282948,48,212,ID123598
199757,chrY,1284368,1284369,Ddx3y,-,0.000000,0.003181,1260770,1286629,1263287,...,1263569,1263700,2,25859,2597,1284321,1284382,61,151,ID123597
199758,chrY,1265577,1265578,Ddx3y,-,0.000000,0.445180,1260770,1286629,1263287,...,1263569,1263700,2,25859,2597,1265574,1265719,145,1273,ID123589

In [33]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [34]:
Positive["m6APosition"] = Positive["m6AStart"] - Positive["exonStart"]
Negative["m6APosition"] = Negative["exonEnd"] - Negative["m6AEnd"]

In [35]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [36]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr1,5084427,5084428,Atp6v1h,+,0.000000,0.077187,5083079,5162529,5084450,...,5150061,2,79450,425,5084416,5084563,147,199,ID147078,11
1,chr1,5084453,5084454,Atp6v1h,+,0.000000,0.063405,5083079,5162529,5084450,...,5150061,2,79450,425,5084416,5084563,147,199,ID147078,37
2,chr1,5084463,5084464,Atp6v1h,+,0.002439,0.250139,5083079,5162529,5084450,...,5150061,2,79450,425,5084416,5084563,147,199,ID147078,47
3,chr1,5084495,5084496,Atp6v1h,+,0.000000,0.008835,5083079,5162529,5084450,...,5150061,2,79450,425,5084416,5084563,147,199,ID147078,79
4,chr1,5084499,5084500,Atp6v1h,+,0.000000,0.045467,5083079,5162529,5084450,...,5150061,2,79450,425,5084416,5084563,147,199,ID147078,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199754,chrY,1280423,1280424,Ddx3y,-,0.000000,0.382121,1260770,1286629,1263287,...,1263700,2,25859,2597,1280309,1280439,130,260,ID123592,15
199755,chrY,1282909,1282910,Ddx3y,-,0.000000,0.155704,1260770,1286629,1263287,...,1263700,2,25859,2597,1282900,1282948,48,212,ID123598,38
199756,chrY,1282917,1282918,Ddx3y,-,0.000000,0.189674,1260770,1286629,1263287,...,1263700,2,25859,2597,1282900,1282948,48,212,ID123598,30
199757,chrY,1284368,1284369,Ddx3y,-,0.000000,0.003181,1260770,1286629,1263287,...,1263700,2,25859,2597,1284321,1284382,61,151,ID123597,13
199758,chrY,1265577,1265578,Ddx3y,-,0.000000,0.445180,1260770,1286629,1263287,...,1263700,2,25859,2597,1265574,1265719,145,1273,ID123589,141

In [37]:
Data = Data.sort_values(by=["ID","m6APosition"], axis=0, ascending=[True,True])
Data = Data.reset_index(drop = True)

In [38]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr9,54708411,54708412,Dnaja4,+,0.000000,0.424143,54699558,54716315,54699728,...,54714370,2,16757,1855,54708382,54708487,105,483,ID120000,29
1,chr9,54708421,54708422,Dnaja4,+,0.001545,0.635691,54699558,54716315,54699728,...,54714370,2,16757,1855,54708382,54708487,105,483,ID120000,39
2,chr9,54708446,54708447,Dnaja4,+,0.000000,0.139425,54699558,54716315,54699728,...,54714370,2,16757,1855,54708382,54708487,105,483,ID120000,64
3,chr9,54714290,54714291,Dnaja4,+,0.000000,0.215374,54699558,54716315,54699728,...,54714370,2,16757,1855,54714269,54714370,101,1047,ID120001,21
4,chr9,54714308,54714309,Dnaja4,+,0.000000,0.026594,54699558,54716315,54699728,...,54714370,2,16757,1855,54714269,54714370,101,1047,ID120001,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199754,chr12,85819548,85819549,0610007P14Rik,-,0.000000,0.150995,85815447,85824522,85816113,...,85816434,2,9075,746,85819478,85819569,91,213,ID163859,20
199755,chr12,85819533,85819534,0610007P14Rik,-,0.000000,0.142697,85815447,85824522,85816113,...,85816434,2,9075,746,85819478,85819569,91,213,ID163859,35
199756,chr12,85819493,85819494,0610007P14Rik,-,0.000000,0.602361,85815447,85824522,85816113,...,85816434,2,9075,746,85819478,85819569,91,213,ID163859,75
199757,chr12,85819484,85819485,0610007P14Rik,-,0.000000,0.555045,85815447,85824522,85816113,...,85816434,2,9075,746,85819478,85819569,91,213,ID163859,84
199758,chr12,85819479,85819480,0610007P14Rik,-,0.000000,0.050251,85815447,85824522,85816113,...,85816434,2,9075,746,85819478,85819569,91,213,ID163859,89

In [39]:
Data["Probabilty"] = Data["IL"] - Data["WT"]

### Heatmap

In [40]:
ID = Data["ID"].to_list()
ID = list(set(ID))

In [41]:
Heatmap = pd.DataFrame({"Index":range(0, 200, 5)})

In [42]:
for i in range(len(ID)):
    df = Data[Data["ID"]==ID[i]]
    df = df.reset_index(drop = True)
    
    Position = df["m6APosition"].to_list()
    # Prob = df["WT"].to_list() # WT
    Prob = df["IL"].to_list() # Mutation
    Dict = dict(zip(Position,Prob))
    
    
    Value = []
    for j in range(40):
        Interval = [k for k in range(j*5,(j+1)*5,1)]
        
        List = []
        for num in Interval:
            if num in Dict.keys():
                List.append(Dict[num])
            if num not in Dict.keys():
                List.append(0)
        Value.append(sum(List)/5)
    
    df = pd.DataFrame({ID[i]:Value})
    Heatmap = pd.merge(Heatmap, df, left_index=True, right_index=True, how='outer')

In [43]:
Heatmap

,Index,ID128202,ID161293,ID147484,ID146384,ID143388,ID161613,ID136096,ID154832,ID143685,...,ID145515,ID159444,ID160810,ID158903,ID132952,ID137723,ID148121,ID150624,ID121409,ID122653
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.108111,0.000000,0.000000,0.000000,0.000000,0.004945,0.013884,0.000000,0.000000
1,5,0.000000,0.000000,0.002376,0.004691,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.049893,0.000000,0.000000,0.000000,0.000000,0.091531
2,10,0.000000,0.000000,0.000000,0.002418,0.000000,0.000000,0.000000,0.000000,0.045305,...,0.000000,0.000000,0.013166,0.002694,0.000000,0.000000,0.000000,0.000000,0.000000,0.024636
3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020298,0.022389,0.018057
4,20,0.031450,0.000000,0.000000,0.000000,0.000000,0.000000,0.035309,0.000000,0.000000,...,0.007261,0.034959,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012889,0.000000
5,25,0.000000,0.000000,0.000000,0.000000,0.047940,0.000000,0.000000,0.000608,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,30,0.000000,0.000000,0.001360,0.000000,0.000000,0.000000,0.109490,0.000000,0.000000,...,0.000000,0.013681,0.000000,0.000000,0.000000,0.001020,0.000000,0.014080,0.000000,0.000000
7,35,0.012635,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027042,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050832
8,40,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,45,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001363,0.000000,...,0.001736,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000668,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,55,0.000000,0.000000,0.000000,0.000000,0.000000,0.013965,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.002537,0.011278,0.000000,0.000000,0.000000,0.000000
12,60,0.092856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001259,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.035651,0.000000,0.000275
13,65,0.000000,0.000000,0.000000,0.000000,0.045920,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.006233,0.033005,0.000000,0.000000,0.000000,0.009297,0.000000,0.000000
14,70,0.025973,0.000000,0.000000,0.000000,0.047240,0.000000,0.000000,0.000000,0.000000,...,0.001069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,75,0.000000,0.000000,0.000000,0.000000,0.052401,0.000000,0.020935,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,80,0.006786,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019007,0.000000,0.000000,0.000000
17,85,0.000000,0.101815,0.000000,0.000000,0.033715,0.086647,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,90,0.000000,0.011112,0.000000,0.000000,0.062029,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.006465,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036947,0.000000,0.000000
20,100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.111194,0.000000,0.024092,0.000000,0.000000,0.000000,0.000000
21,105,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009753,0.071969,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,110,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.004152,0.000000,0.000000,0.000484,0.000000,0.000000,0.000000
23,115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028102,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,120,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.003122,0.000000,0.000000,0.000000,0.000000
25,125,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,130,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.071224,0.000000,0.000000
27,135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.006285,0.000000,0.000000,0.000000,0.000000
28,140,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001023
29,145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.039208,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,150,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036568,0.000000,0.003127
31,155,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,160,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.049719,0.000000,0.000000
33,165,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.005838,0.000000,0.000000,0.000000,0.000000
34,170,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,175,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.103531,0.000000,0.000000,0.000000,0.111890,0.000000,0.000000
36,180,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011965,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060769,0.000000,0.000000
38,190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.038335,0.000000,0.000000,0.000000,0.000000
39,195,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.020004,0.000000,0.000000,0.000000,0.000000

In [44]:
Heatmap.to_csv("mm10_Heatmap_iM6A_IL_LongInternalExonStart_4.csv", index=0)