In [1]:
from Bio import SeqIO
from Bio.Seq import Seq
import numpy as np
import pandas as pd
import random

In [2]:
meta=[]
sequence=[]

In [3]:
seq = ('Temp/MultiExon.txt')

In [4]:
for seq_record in SeqIO.parse(seq, "fasta"):
    meta.append(str(seq_record.id))
    sequence.append(str(seq_record.seq))

In [5]:
Fasta = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})

In [6]:
Fasta

,Meta,Sequence
0,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...
17577,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [7]:
Data = pd.read_csv("Temp/MultiExon.csv")

In [8]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2

In [9]:
Result = pd.merge(Data, Fasta, left_index=True, right_index=True, how='outer')

In [10]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,Meta,Sequence
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2,chr1:134199224-134235431(-),ACTCAGCTCCCGCGCCGGGGGCGACGAAGGCGCCGGCGCCAGAGTG...
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2,chr1:8361474-9299238(-),CTTCGCGGCGATACAGCCTCTCGGAAACAAAGGTATCCCTAGCCTT...
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2,chr1:25067549-25829707(-),GGCTCTGGCCGCTGGATACCACCGCCCCCCCCCCTATTATTTTTTT...
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2,chr1:33453809-33669795(-),CTTCCCGTTCCAAATGAACTCTCCCGCCACTGGGAGAGAGCGGCTG...
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2,chr1:58711559-58758884(+),GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2,chr19:60198585-60226697(-),GACACGATGTTGGCGGGGTTCTAAGATGGCCGCCGAGCCGCTGTTT...
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2,chr19:60761115-60790693(-),GGCGCTGCCGCCGCGAGGGAATCACGTGGTTCCTTCCTTTCCGTCT...
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2,chr19:60838747-60861479(-),GGGTTCTGGGGCGGGACACGCTGATAGGCTCCACCCCTTGCGCTGC...
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2,chr19:60864050-60874556(-),AGAAGCCACGCCCCAGGCAGAAGCACACCCGGCGTGCTCCGGCTAC...
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2,chr19:61224401-61228418(-),GGGAGACAGACGGACAGACGGACGGACACAGACGCTGCGCCCAGGC...

In [11]:
Result.drop(["Meta","Sequence"], axis=1, inplace=True)

In [12]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2

In [13]:
Result["GeneLength"] = Result["txEnd"] - Result["txStart"]
Result["LastExonLength"] = Result["LastExonEnd"] - Result["LastExonStart"]

In [14]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590,134234014,134234412,2,36207,4366
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633,8414202,8414313,2,937764,2159
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356,25074684,25074789,2,762158,807
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304,33464052,33464121,2,215986,495
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884,58752338,58752846,2,47325,5101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17577,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487,60199969,60200076,2,28112,902
17578,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304,60763064,60763264,2,29578,1189
17579,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050,60842118,60842236,2,22732,303
17580,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719,60865165,60865331,2,10506,669
17581,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033,61225132,61225214,2,4017,632

In [15]:
Data = Result

In [16]:
LongInternalExon = pd.read_csv("/home/morgenlefay/iM6A/Chapter2/Figure1/mm10_InternalExon.csv")

In [17]:
LongInternalExon

        chrom  exonStart    exonEnd           name strand  ExonLength  Start
0        chr7   89935726   89935964          l7Rn6      -         238    217
1        chr7   89923563   89923715          l7Rn6      -         152    455
2        chr7   89920072   89920191          l7Rn6      -         119    607
3        chr2  155045611  155045781              a      +         170    111
4        chr2  155047675  155047740              a      +          65    281
...       ...        ...        ...            ...    ...         ...    ...
163855  chr18   38258269   38258362  0610009O20Rik      +          93   1179
163856  chr18   38254279   38254368  0610009O20Rik      +          89    691
163857  chr12   85822087   85822248  0610007P14Rik      -         161     52
163858  chr12   85816315   85816434  0610007P14Rik      -         119    304
163859  chr12   85819478   85819569  0610007P14Rik      -          91    213

[163860 rows x 7 columns]

In [18]:
LongInternalExon = LongInternalExon.reset_index(drop = False)
LongInternalExon["index"] = LongInternalExon["index"].astype(str)
LongInternalExon["ID"] = "ID"+ LongInternalExon["index"]
LongInternalExon.drop(["index"], axis=1,inplace=True)

In [19]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
0,chr7,89935726,89935964,l7Rn6,-,238,217,ID0
1,chr7,89923563,89923715,l7Rn6,-,152,455,ID1
2,chr7,89920072,89920191,l7Rn6,-,119,607,ID2
3,chr2,155045611,155045781,a,+,170,111,ID3
4,chr2,155047675,155047740,a,+,65,281,ID4
...,...,...,...,...,...,...,...,...
163855,chr18,38258269,38258362,0610009O20Rik,+,93,1179,ID163855
163856,chr18,38254279,38254368,0610009O20Rik,+,89,691,ID163856
163857,chr12,85822087,85822248,0610007P14Rik,-,161,52,ID163857
163858,chr12,85816315,85816434,0610007P14Rik,-,119,304,ID163858
163859,chr12,85819478,85819569,0610007P14Rik,-,91,213,ID163859

In [20]:
LongInternalExon = LongInternalExon.iloc[80000:120000]

In [21]:
LongInternalExon

,chrom,exonStart,exonEnd,name,strand,ExonLength,Start,ID
80000,chr16,17522557,17522723,Lztr1,+,166,1500,ID80000
80001,chr16,17523276,17523433,Lztr1,+,157,1836,ID80001
80002,chr16,17520890,17521046,Lztr1,+,156,1044,ID80002
80003,chr16,17524307,17524457,Lztr1,+,150,2120,ID80003
80004,chr16,17519386,17519526,Lztr1,+,140,702,ID80004
...,...,...,...,...,...,...,...,...
119995,chr16,22869415,22869473,Dnajb11,+,58,879,ID119995
119996,chr8,83609813,83610394,Dnajb1,+,581,368,ID119996
119997,chr9,54710501,54710732,Dnaja4,+,231,816,ID119997
119998,chr9,54709132,54709360,Dnaja4,+,228,588,ID119998
119999,chr9,54706062,54706243,Dnaja4,+,181,302,ID119999

In [22]:
M6A = pd.read_csv("/home/morgenlefay/iM6A/Chapter3/Figure1/iM6A_Mouse_IL.csv")

In [23]:
M6A

        chrom     Start       End     name strand        WT        IL
0        chr1   3214485   3214486     Xkr4      -  0.000000  0.000000
1        chr1   3214554   3214555     Xkr4      -  0.000000  0.000000
2        chr1   3214662   3214663     Xkr4      -  0.199716  0.199716
3        chr1   3214724   3214725     Xkr4      -  0.152102  0.152101
4        chr1   3214732   3214733     Xkr4      -  0.652838  0.652836
...       ...       ...       ...      ...    ...       ...       ...
1769220  chrY  10433185  10433186  Gm28510      +  0.000000  0.001592
1769221  chrY  51866751  51866752  Gm20920      +  0.000000  0.001402
1769222  chrY  64487901  64487902  Gm20908      +  0.000000  0.001402
1769223  chrY  74478146  74478147  Gm29110      +  0.000000  0.077403
1769224  chrY  75203467  75203468  Gm20814      +  0.000000  0.072174

[1769225 rows x 7 columns]

In [24]:
M6A.columns = ["chrom","m6AStart","m6AEnd","name","strand","WT","IL"]

In [25]:
Data = pd.merge(M6A, Data, how="inner", on=["chrom","name","strand"])

In [26]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength
0,chr1,3214485,3214486,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
1,chr1,3214554,3214555,Xkr4,-,0.000000,0.000000,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
2,chr1,3214662,3214663,Xkr4,-,0.199716,0.199716,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
3,chr1,3214724,3214725,Xkr4,-,0.152102,0.152101,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
4,chr1,3214732,3214733,Xkr4,-,0.652838,0.652836,3214481,3671498,3216021,...,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,3421701,3421901,2,457017,2487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589988,chrY,90793403,90793404,Erdr1,+,0.232404,0.259672,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589989,chrY,90793407,90793408,Erdr1,+,0.218156,0.176900,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589990,chrY,90816374,90816375,Erdr1,+,0.000000,0.020307,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589991,chrY,90816408,90816409,Erdr1,+,0.000000,0.003735,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29
1589992,chrY,90816418,90816419,Erdr1,+,0.000000,0.002582,90785441,90816464,90785670,...,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,90816348,90816433,2,31023,29

In [27]:
Data = pd.merge(Data, LongInternalExon, how="inner", on=["chrom","name","strand"])

In [28]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,4807850,4807851,Lypla1,+,0.0,0.000000,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4840955,4841132,177,553,ID80124
1,chr1,4807850,4807851,Lypla1,+,0.0,0.000000,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4839386,4839488,102,451,ID80125
2,chr1,4807850,4807851,Lypla1,+,0.0,0.000000,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4837000,4837074,74,377,ID80126
3,chr1,4807850,4807851,Lypla1,+,0.0,0.000000,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
4,chr1,4807850,4807851,Lypla1,+,0.0,0.000000,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4828583,4828649,66,192,ID80128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5318340,chrY,90816374,90816375,Erdr1,+,0.0,0.020307,90785441,90816464,90785670,...,90816348,90816433,2,31023,29,90816348,90816433,85,660,ID113115
5318341,chrY,90816408,90816409,Erdr1,+,0.0,0.003735,90785441,90816464,90785670,...,90816348,90816433,2,31023,29,90793295,90793417,122,538,ID113114
5318342,chrY,90816408,90816409,Erdr1,+,0.0,0.003735,90785441,90816464,90785670,...,90816348,90816433,2,31023,29,90816348,90816433,85,660,ID113115
5318343,chrY,90816418,90816419,Erdr1,+,0.0,0.002582,90785441,90816464,90785670,...,90816348,90816433,2,31023,29,90793295,90793417,122,538,ID113114
5318344,chrY,90816418,90816419,Erdr1,+,0.0,0.002582,90785441,90816464,90785670,...,90816348,90816433,2,31023,29,90816348,90816433,85,660,ID113115

In [29]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [30]:
Positive = Positive[(Positive["m6AStart"]>=Positive["exonStart"]) & (Positive["m6AEnd"]<=Positive["exonEnd"])]
Negative = Negative[(Negative["m6AStart"]>=Negative["exonStart"]) & (Negative["m6AEnd"]<=Negative["exonEnd"])]

In [31]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [32]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonStart,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID
0,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
1,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
2,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
3,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
4,chr1,4832377,4832378,Lypla1,+,0.0,0.006360,4807822,4846739,4807913,...,4840955,4841132,2,38917,1777,4832310,4832381,71,306,ID80127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191641,chrY,89724896,89724897,Gm21996,-,0.0,0.039020,89713423,89745532,89713627,...,89714015,89714114,2,32109,234,89724833,89724900,67,278,ID101758
191642,chrY,89731959,89731960,Gm21996,-,0.0,0.070523,89713423,89745532,89713627,...,89714015,89714114,2,32109,234,89731936,89731971,35,243,ID101759
191643,chrY,89744025,89744026,Gm21996,-,0.0,0.012377,89713423,89745532,89713627,...,89714015,89714114,2,32109,234,89743993,89744125,132,44,ID101753
191644,chrY,89744046,89744047,Gm21996,-,0.0,0.663240,89713423,89745532,89713627,...,89714015,89714114,2,32109,234,89743993,89744125,132,44,ID101753
191645,chrY,89744124,89744125,Gm21996,-,0.0,0.000000,89713423,89745532,89713627,...,89714015,89714114,2,32109,234,89743993,89744125,132,44,ID101753

In [33]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [34]:
Positive["m6APosition"] = Positive["m6AStart"] - Positive["exonStart"]
Negative["m6APosition"] = Negative["exonEnd"] - Negative["m6AEnd"]

In [35]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [36]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,4841132,2,38917,1777,4832310,4832381,71,306,ID80127,15
1,chr1,4832325,4832326,Lypla1,+,0.0,0.491227,4807822,4846739,4807913,...,4841132,2,38917,1777,4832310,4832381,71,306,ID80127,15
2,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,4841132,2,38917,1777,4832310,4832381,71,306,ID80127,54
3,chr1,4832364,4832365,Lypla1,+,0.0,0.007634,4807822,4846739,4807913,...,4841132,2,38917,1777,4832310,4832381,71,306,ID80127,54
4,chr1,4832377,4832378,Lypla1,+,0.0,0.006360,4807822,4846739,4807913,...,4841132,2,38917,1777,4832310,4832381,71,306,ID80127,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191641,chrY,89724896,89724897,Gm21996,-,0.0,0.039020,89713423,89745532,89713627,...,89714114,2,32109,234,89724833,89724900,67,278,ID101758,3
191642,chrY,89731959,89731960,Gm21996,-,0.0,0.070523,89713423,89745532,89713627,...,89714114,2,32109,234,89731936,89731971,35,243,ID101759,11
191643,chrY,89744025,89744026,Gm21996,-,0.0,0.012377,89713423,89745532,89713627,...,89714114,2,32109,234,89743993,89744125,132,44,ID101753,99
191644,chrY,89744046,89744047,Gm21996,-,0.0,0.663240,89713423,89745532,89713627,...,89714114,2,32109,234,89743993,89744125,132,44,ID101753,78
191645,chrY,89744124,89744125,Gm21996,-,0.0,0.000000,89713423,89745532,89713627,...,89714114,2,32109,234,89743993,89744125,132,44,ID101753,0

In [37]:
Data = Data.sort_values(by=["ID","m6APosition"], axis=0, ascending=[True,True])
Data = Data.reset_index(drop = True)

In [38]:
Data

,chrom,m6AStart,m6AEnd,name,strand,WT,IL,txStart,txEnd,cdsStart,...,SecondToLastExonEnd,Group,GeneLength,LastExonLength,exonStart,exonEnd,ExonLength,Start,ID,m6APosition
0,chr5,18308628,18308629,Gnai1,-,0.0,0.003533,18265134,18360355,18267018,...,18271979,2,95221,2075,18308552,18308694,142,347,ID100000,65
1,chr5,18308574,18308575,Gnai1,-,0.0,0.026446,18265134,18360355,18267018,...,18271979,2,95221,2075,18308552,18308694,142,347,ID100000,119
2,chr5,18308565,18308566,Gnai1,-,0.0,0.031859,18265134,18360355,18267018,...,18271979,2,95221,2075,18308552,18308694,142,347,ID100000,128
3,chr5,18273566,18273567,Gnai1,-,0.0,0.018567,18265134,18360355,18267018,...,18271979,2,95221,2075,18273445,18273575,130,776,ID100001,8
4,chr5,18273510,18273511,Gnai1,-,0.0,0.062510,18265134,18360355,18267018,...,18271979,2,95221,2075,18273445,18273575,130,776,ID100001,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191641,chr5,18271935,18271936,Gnai1,-,0.0,0.035501,18265134,18360355,18267018,...,18271979,2,95221,2075,18271825,18271979,154,906,ID99999,43
191642,chr5,18271932,18271933,Gnai1,-,0.0,0.036544,18265134,18360355,18267018,...,18271979,2,95221,2075,18271825,18271979,154,906,ID99999,46
191643,chr5,18271917,18271918,Gnai1,-,0.0,0.089121,18265134,18360355,18267018,...,18271979,2,95221,2075,18271825,18271979,154,906,ID99999,61
191644,chr5,18271893,18271894,Gnai1,-,0.0,0.118607,18265134,18360355,18267018,...,18271979,2,95221,2075,18271825,18271979,154,906,ID99999,85
191645,chr5,18271884,18271885,Gnai1,-,0.0,0.157501,18265134,18360355,18267018,...,18271979,2,95221,2075,18271825,18271979,154,906,ID99999,94

In [39]:
Data["Probabilty"] = Data["IL"] - Data["WT"]

### Heatmap

In [40]:
ID = Data["ID"].to_list()
ID = list(set(ID))

In [41]:
Heatmap = pd.DataFrame({"Index":range(0, 200, 5)})

In [42]:
for i in range(len(ID)):
    df = Data[Data["ID"]==ID[i]]
    df = df.reset_index(drop = True)
    
    Position = df["m6APosition"].to_list()
    Prob = df["Probabilty"].to_list()
    Dict = dict(zip(Position,Prob))
    
    
    Value = []
    for j in range(40):
        Interval = [k for k in range(j*5,(j+1)*5,1)]
        
        List = []
        for num in Interval:
            if num in Dict.keys():
                List.append(1)
            if num not in Dict.keys():
                List.append(0)
        Value.append(sum(List)/5)
    
    df = pd.DataFrame({ID[i]:Value})
    Heatmap = pd.merge(Heatmap, df, left_index=True, right_index=True, how='outer')

In [43]:
Heatmap

,Index,ID86283,ID95540,ID110820,ID91613,ID116650,ID93693,ID102883,ID101053,ID90231,...,ID110445,ID90336,ID96365,ID83566,ID105419,ID108348,ID96600,ID104198,ID104977,ID81866
0,0,0.2,0.2,0.0,0.2,0.0,0.0,0.2,0.0,0.0,...,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2
3,15,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.2,0.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0
5,25,0.2,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,30,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0
7,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,40,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,...,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0
9,45,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.2,...,0.2,0.0,0.2,0.0,0.0,0.0,0.0,0.2,0.0,0.0
10,50,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0,0.0
11,55,0.0,0.0,0.0,0.2,0.0,0.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0
12,60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,...,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0
13,65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2
14,70,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.2,0.0
15,75,0.0,0.2,0.2,0.0,0.0,0.2,0.0,0.0,0.0,...,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,80,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.2,0.0,0.2,0.0,0.0,0.0
17,85,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0
18,90,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,95,0.0,0.0,0.2,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.2,0.0
20,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0
21,105,0.2,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0
23,115,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,130,0.0,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0
27,135,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,170,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
Heatmap.to_csv("mm10_Heatmap_RAC_LongInternalExonStart_3.csv", index=0)