In [1]:
import numpy as np
import pandas as pd

In [2]:
Fasta = pd.read_csv("mm10_Fasta_Non_Donor_Acceptor_Replace.csv")

In [3]:
Fasta

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,...,LastIntronLength,SecondToLastLength,Pre,PreSequence,SecondToLastExonSequence,LastIntronSequence,LastExonSequence,Truncation,Seq,Replace
0,Pdcd11,chr19,+,47090765,47131143,47092798,47130810,36,"47090765,47092781,47093750,47095207,47096854,4...","47090867,47092900,47093882,47095375,47097016,4...",...,525,166,39182,AGAACGGAAGTAGCCCTGGTCTTACCTACGCTCGTGGACGAGTCGC...,ATGTGGATGTGATCGTCAAGTTTGCCCAGCTGGAGTTCCAGCTCGG...,GTGAGGGCGACAGCAGGGCTCATTCCTGTTGGAGTGTGGGCTGGGA...,GGACATCTTTGAGCGGGTCATTCACCTGAGCCTGGCGCCTAAGAGG...,GTGAGGGCGACAGCAGGGCTCATTCCTGTTGGAGTGTGGGCTGGGA...,ATGTGGATGTGATCGTCAAGTTTGCCCAGCTGGAGTTCCAGCTCGG...,CCACTGTCACTCACAGCACCAGCAGCCAGTCACAGATGGGGGCAAG...
1,Gna13,chr11,+,109362830,109401369,109362973,109396486,4,"109362830,109365535,109392345,109395913,","109363256,109365762,109392396,109401369,",...,3517,51,29515,AGTCCTCGGGTTCCCTCCCTCCCCGGGCGCGCTCGGGCCGCCGCTG...,GGTGAGTCTGTAAAGTATTTCTTGGATAACTTGGATAAACTTGGAG...,GTAAGTTTCAAAACAATAGTTCTGGTTTTGCCTTCAACAGTTGATA...,GATTACATTCCATCACAGCAAGATATCCTGCTTGCCAGAAGGCCCA...,GTAAGTTTCAAAACAATAGTTCTGGTTTTGCCTTCAACAGTTGATA...,GCAGAGTCTGTAAAGTATTTCTTGGATAACTTGGATAAACTTGGAG...,GCTCTTCTTGCCTAGCTTCAAGTCCCAGGCTGTGTATTTTTTTTCA...
2,Wscd2,chr5,+,113490446,113589725,113550934,113588145,9,"113490446,113550422,113558348,113560900,113570...","113490940,113551334,113558463,113561085,113570...",...,10329,201,86816,CACGCTGAACACCCATCAACAAAACTGTCCTTTGTTGGATTTCTTT...,GGTTCAAAGGTGAGCGGGACCACTGGCGAAGCGGGCGGACCATCTG...,GTGACAGGAGGGAGGGTCGTGGACAGTGTGAGGTGCGGGTAATCAG...,AGTGGCCCGAGTTCGTGAGGAACTATGCCCCGTGGTGGGCCACGCA...,GTGACAGGAGGGAGGGTCGTGGACAGTGTGAGGTGCGGGTAATCAG...,GGTTCAAAGCAGAGCGGGACCACTGGCGAAGCGGGCGGACCATCTG...,CCTTTGCAAAGGTCGGTTCTCTTCACTGAACAGCACTATAGCGAAC...
3,Trim80,chr11,+,115440544,115448270,115440553,115448220,8,"115440544,115440706,115441080,115445015,115445...","115440606,115440750,115441745,115445111,115445...",...,843,63,6213,AGAGAGACCATGAAACAGCGGCCACAGAGAAAGGAGAGAAGACGGC...,GAATCAGGATGAGCTCCTATGAGGTGCTGCCCGGAACTGTGGAGAG...,GTGAGTTCTCAAACCAGAGGCCAACCCTGGGGGAGGAGAGGAGGGA...,ATTACTGCAACCTGAACTTTGACCCCTGCACGGCCAGCGAAGAGCT...,GTGAGTTCTCAAACCAGAGGCCAACCCTGGGGGAGGAGAGGAGGGA...,GAATCAGGATGAGCTCCTATGAGGTGCTGCCCGGAACTGTGGAGAG...,AGCAGTTCCGCAATCCTTCAGGACCTGTCGTGGACTTACCCAGCAC...
4,Strbp,chr2,-,37569867,37647285,37584029,37647118,17,"37569867,37586509,37590656,37596703,37599120,3...","37584106,37586554,37590780,37596844,37599255,3...",...,2403,45,60731,GTGTATTCCAGAGAACAATTTTGAGATATCTTTGCTTATATTTGAC...,GTTACGGAACCCCATATGGTTACAGCACAGCTGCCCCTGCATATG,GTATGTACACTTCCTTACTGATTCCTCCTCTTAGCAAATTTGTCAC...,GTTTGCCCAAGAGAATGGTTCTGTTACCCGTTATGAAATTCCCAAC...,GTATGTACACTTCCTTACTGATTCCTCCTCTTAGCAAATTTGTCAC...,GTTACGGAACCCCATATGGTTACAGCACAGCTGCCCCTGCATATGC...,TCCCGTTTCCCCTCGGCGCTGACCTGGTGGCTGGTCCAGGCTGTGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2321,Inpp4a,chr1,+,37299890,37410736,37357918,37408259,26,"37299890,37357342,37357814,37358507,37364109,3...","37300118,37357404,37358024,37358552,37364228,3...",...,9206,155,98875,GCGGGGTTGTGCGCTGTGTTCTGAGAGAAGGCGGTGGCAGGATTCG...,GTCTGTCGCCGCCTTAACGGGGTCCGATTCACCAGCTGCAAGAGTG...,GTGAGTGAGGCTGCTGCCAGGCTGCATCTGCCCAGCCACTTGCTCT...,TGAGGGTTGTCGGCGAGAAAACACAATGAAGAATGTTGGAAGTCGC...,GTGAGTGAGGCTGCTGCCAGGCTGCATCTGCCCAGCCACTTGCTCT...,GTCTGTCGCCGCCTTAACGGGGTCCGATTCACCAGCTGCAAGAGTG...,CATCGAGTGAAAAGAAAACTGAAGTCAAACCGTCTTCCAATGGTTC...
2322,Trps1,chr15,-,50654751,50889691,50660674,50846940,6,"50654751,50664686,50822104,50830828,50846013,5...","50661736,50664809,50822708,50831958,50846942,5...",...,2950,123,224882,TGCAAACAACAGAAGACGGTTCATGGCTCTGGCCGCCGCGCCACCA...,AGGCGAAGAGGATCTGGTGTTTTTTGTGCCAATTGCCTGACCACAA...,GTAAGAACTTATCCTAGCCCTTTAGGGGAAGCTTACACAGATGAGC...,ACTCCCAGGCCTTTAAACATCATTAAACAAAACAACGGCGAGCAGA...,GTAAGAACTTATCCTAGCCCTTTAGGGGAAGCTTACACAGATGAGC...,AGGCGAAGAGGATCTGGTGTTTTTTGTGCCAATTGCCTGACCACAA...,GCGCCGAGCTCCCCCGACCCTGCCCTCCATCCTCTAGCGCAGCCCT...
2323,Scn7a,chr2,-,66673424,66784914,66675497,66757357,25,"66673424,66680074,66680863,66682704,66683266,6...","66676561,66680345,66680968,66682842,66683320,6...",...,3513,271,104569,ATCTGTCTGTAGGTGGTCTCTGGGTCTGTGGAGCTAGCCTGGTGGC...,AACAAATTCCAAGGCTTCCTTTTTGACCTAGTAACACACCGTGTCT...,GTAAGGTTGGCTCTTGTCATTTTTCTTTAGAATATTACTTCAGTCT...,GGCTGCTGCTACCCTTGACAATAGGACAATACTTTGTGCCTCCTTC...,GTAAGGTTGGCTCTTGTCATTTTTCTTTAGAATATTACTTCAGTCT...,AACAAATTCCAAGGCTTCCTTTTTGACCTAGTAACACACCGTGTCT...,AGCCTGTCACACAGGAGGATGGTAAAGAGAGTCGCATCTCAGTGCA...
2324,Zfp946,chr17,+,22424258,22456689,22451122,22455838,7,"22424258,22428480,22444167,22446796,22451096,2...","22424429,22428565,22444291,22446893,22451152,2...",...,845,127,29193,GGAAAATTCACCATTCCCTTAGGTACTTAAGTGAACAACTTGTTCT...,GATCTGTTAAGATTCAAGGACGTGGCTGTGGAATTCTCACAGGAGG...,GTAAGAATACTCTTCATGTAAAATTCTTGATTCCTTCTTTGAATTT...,TTTTTTCAGAAAATGATCATATATGTTACAAATATAAGAATGTCTT...,GTAAGAATACTCTTCATGTAAAATTCTTGATTCCTTCTTTGAATTT...,GATCTGTTAAGATTCAAGGACGTGGCTGTGGAATTCTCACAGGAGG...,CACTCATGAAACCCAGTCACGTCATTGTGGAGACCATGATGTGAGG...
2325,Kif16b,chr2,-,142617473,142901531,142619757,142901371,26,"142617473,142648427,142672288,142690578,142702...","142619916,142648511,142672378,142690701,142702...",...,28511,84,253020,GGCAGGTGTGGCCGCCTAGCAACTCCAGGTCGGCCCTAGCCGAGGG...,CTCGCTGCTCTTGAATTCCCCCCAAAGAAGCTGTTTGGAAACAAAG...,GTAAGAGAGCAAGCTTTTCACCTCCCTGTGTAGAAAAATCCACCAT...,AAATACCTCAGGGAGTTTTTCAGTGTGATGCTCCAGTCCGAGACAT...,GTAAGAGAGCAAGCTTTTCACCTCCCTGTGTAGAAAAATCCACCAT...,CTCGCTGCTCTTGAATTCCCCCCAAAGAAGCTGTTTGGAAACAAAG...,ACCTGGATCAGAGACTCACTCCAGGTGTACCATGAGCCGAGCTCGG...

### Enhancer

In [4]:
Enhancer = pd.read_csv("Mouse_Motif_Regression_LastExon.csv")

In [5]:
Enhancer

       Name     Slope  Intercept  Pvalue        R2
0     GGACT  0.117800  -0.014730     0.0  0.055643
1     GAACT  0.101502  -0.014394     0.0  0.046392
2     TGGAC  0.096929  -0.014776     0.0  0.038428
3     GGACA  0.082938  -0.014563     0.0  0.034612
4     AGACT  0.081404  -0.014772     0.0  0.029159
...     ...       ...        ...     ...       ...
1019  AGGTC -0.049309  -0.015207     0.0  0.003481
1020  CAGGT -0.050436  -0.015226     0.0  0.004501
1021  TAGGT -0.051298  -0.015193     0.0  0.002082
1022  TCGAC -0.052638  -0.015186     0.0  0.002278
1023  AGGTA -0.054098  -0.015178     0.0  0.003969

[1024 rows x 5 columns]

In [6]:
Enhancer = Enhancer.head(200)

In [7]:
Enhancer = Enhancer["Name"].to_list()

In [8]:
motif_dic = dict()
positions = range(0, 210)
posi_str = []
for element in positions:
    posi_str.append(str(element))
motif_dic = dict.fromkeys(posi_str, 0)

In [9]:
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=110:
        Seq = Fasta.loc[i,"LastIntronSequence"][0:50] + Fasta.loc[i,"LastIntronSequence"][-50:] + Fasta.loc[i,"LastExonSequence"][0:110]
        
    if Fasta.loc[i,"LastExonLength"]<110:        
        Seq = Fasta.loc[i,"LastIntronSequence"][0:50] + Fasta.loc[i,"LastIntronSequence"][-50:] + Fasta.loc[i,"LastExonSequence"]
        
    for j in range(0, len(Seq)-6, 1):
        string = Seq[j:j+5]
        if(string in Enhancer):
            motif_dic[str(j)]+=1

In [10]:
Position = pd.DataFrame({"Index":range(0, 210)})

In [11]:
Value=[]
for i in range(0,210,1):
    Value.append(int(motif_dic[str(i)]))
Position["Enhancer"]=Value

In [12]:
Position

     Index  Enhancer
0        0         1
1        1       527
2        2       357
3        3       271
4        4       234
..     ...       ...
205    205         0
206    206         0
207    207         0
208    208         0
209    209         0

[210 rows x 2 columns]

In [13]:
df = pd.DataFrame({"Index":range(0, 210)})
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=110:
        Seq = Fasta.loc[i,"Seq"][(Fasta.loc[i,"SecondToLastLength"]):(Fasta.loc[i,"SecondToLastLength"]+100)] + Fasta.loc[i,"Seq"][-(Fasta.loc[i,"LastExonLength"]):][0:110]
        
    if Fasta.loc[i,"LastExonLength"]<110:        
        Seq = Fasta.loc[i,"Seq"][(Fasta.loc[i,"SecondToLastLength"]):(Fasta.loc[i,"SecondToLastLength"]+100)] + Fasta.loc[i,"Seq"][-(Fasta.loc[i,"LastExonLength"]):]
        
    seq = Seq
    if len(seq) >= 210:
        lis = [1]*210
    if len(seq) < 210:
        lis = [1]*len(seq) + [0]*(210-len(seq))
        
    New = np.array(lis)
    New = pd.DataFrame({Fasta.loc[i,"name"]:New})
    df = pd.merge(df, New, left_index=True, right_index=True)

In [14]:
df.drop(["Index"], axis=1, inplace=True)
df = df.T

In [15]:
df.loc["col_sum"] = df.sum()
df = df.T

In [16]:
Number = df[["col_sum"]]

In [17]:
Number.columns = ["Number"]

In [18]:
Data = pd.concat([Position, Number], axis=1)

In [19]:
Data

     Index  Enhancer  Number
0        0         1    2326
1        1       527    2326
2        2       357    2326
3        3       271    2326
4        4       234    2326
..     ...       ...     ...
205    205         0    2307
206    206         0    2307
207    207         0    2307
208    208         0    2307
209    209         0    2307

[210 rows x 3 columns]

In [20]:
Data["Mean"] = Data["Enhancer"]/Data["Number"]

In [21]:
Data.to_csv("Enhancer_LastExonStart.csv", index=0)

### Silencer

In [22]:
Silencer = pd.read_csv("Mouse_Motif_Regression_LastExon.csv")

In [23]:
Silencer = Silencer.tail(200)

In [24]:
Silencer = Silencer["Name"].to_list()

In [25]:
motif_dic = dict()
positions = range(0, 210)
posi_str = []
for element in positions:
    posi_str.append(str(element))
motif_dic = dict.fromkeys(posi_str, 0)

In [26]:
for i in range(len(Fasta)):
    if Fasta.loc[i,"LastExonLength"]>=110:
        Seq = Fasta.loc[i,"LastIntronSequence"][0:50] + Fasta.loc[i,"LastIntronSequence"][-50:] + Fasta.loc[i,"LastExonSequence"][0:110]
        
    if Fasta.loc[i,"LastExonLength"]<110:        
        Seq = Fasta.loc[i,"LastIntronSequence"][0:50] + Fasta.loc[i,"LastIntronSequence"][-50:] + Fasta.loc[i,"LastExonSequence"]
        
    for j in range(0, len(Seq)-6, 1):
        string = Seq[j:j+5]
        if(string in Silencer):
            motif_dic[str(j)]+=1

In [27]:
Position = pd.DataFrame({"Index":range(0, 210)})

In [28]:
Value=[]
for i in range(0,210,1):
    Value.append(int(motif_dic[str(i)]))
Position["Silencer"]=Value

In [29]:
Position

     Index  Silencer
0        0      1590
1        1       492
2        2       687
3        3       711
4        4       740
..     ...       ...
205    205         0
206    206         0
207    207         0
208    208         0
209    209         0

[210 rows x 2 columns]

In [30]:
Data = pd.concat([Position, Number], axis=1)

In [31]:
Data

     Index  Silencer  Number
0        0      1590    2326
1        1       492    2326
2        2       687    2326
3        3       711    2326
4        4       740    2326
..     ...       ...     ...
205    205         0    2307
206    206         0    2307
207    207         0    2307
208    208         0    2307
209    209         0    2307

[210 rows x 3 columns]

In [32]:
Data["Mean"] = Data["Silencer"]/Data["Number"]

In [33]:
Data.to_csv("Silencer_LastExonStart.csv", index=0)