### Fasta2CSV

In [1]:
from Bio import SeqIO
from Bio.Seq import Seq
import numpy as np
import pandas as pd
import random

In [2]:
Data = pd.read_csv("Temp/mm10.csv")

In [3]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884
...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033

In [4]:
Data["GeneLength"] = Data["txEnd"] - Data["txStart"]

In [5]:
Data = Data.sort_values(by=["chrom","txStart"], axis=0, ascending=True)
Data = Data.reset_index(drop = True)

In [6]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,GeneLength
0,Xkr4,chr1,-,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
1,Rp1,chr1,-,4290845,4409241,4292980,4409187,4,"4290845,4351909,4352201,4409169,","4293012,4352081,4352837,4409241,",4290845,4293012,118396
2,Sox17,chr1,-,4491389,4497354,4491715,4495155,4,"4491389,4493771,4495135,4496290,","4492668,4493863,4495942,4497354,",4491389,4492668,5965
3,Mrpl15,chr1,-,4773210,4785739,4776463,4785677,5,"4773210,4777524,4782567,4783950,4785572,","4776801,4777648,4782733,4784105,4785739,",4773210,4776801,12529
4,Lypla1,chr1,+,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Gm28102,chrY,+,88053314,88079494,88054737,88079297,10,"88053314,88054723,88060190,88060879,88067942,8...","88053358,88054855,88060257,88060914,88068009,8...",88079267,88079494,26180
19629,Gm21294,chrY,+,89052805,89079015,89054243,89078823,10,"89052805,89054226,89059689,89060409,89067478,8...","89052861,89054361,89059756,89060444,89067545,8...",89078793,89079015,26210
19630,Gm21996,chrY,-,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109
19631,Gm20837,chrY,+,90401247,90433263,90402678,90433059,8,"90401247,90402661,90414096,90414713,90429592,9...","90401303,90402796,90414163,90414748,90429710,9...",90433029,90433263,32016
19632,Erdr1,chrY,+,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023

In [7]:
Exon = pd.read_csv("/home/morgenlefay/iM6A/Chapter2/Figure1/MouseExonBed.csv")

In [8]:
Exon

,chrom,Start,End,name,ExonOrder,strand,Interval,ExonLength,CumSum
0,chr19,47090765,47090867,Pdcd11,1,+,-1,102,102
1,chr19,47092781,47092900,Pdcd11,2,+,0,119,221
2,chr19,47093750,47093882,Pdcd11,3,+,0,132,353
3,chr19,47095207,47095375,Pdcd11,4,+,0,168,521
4,chr19,47096854,47097016,Pdcd11,5,+,0,162,683
...,...,...,...,...,...,...,...,...,...
206530,chr3,95132824,95132913,Scnm1,5,-,0,89,511
206531,chr3,95130163,95130358,Scnm1,6,-,2,195,706
206532,chr3,95129535,95129883,Scnm1,7,-,-1,348,1054
206533,chr14,52899968,52900020,Trav4d-3,1,+,0,52,52
206534,chr14,52900191,52900470,Trav4d-3,2,+,1,279,331

In [9]:
M6A = pd.read_csv("iM6A_Mouse_LastIntronDeletion.csv")

In [10]:
M6A

        chrom     Start       End   name strand        WT  Deletion
0        chr1   3214485   3214486   Xkr4      -  0.000000  0.000000
1        chr1   3214554   3214555   Xkr4      -  0.000000  0.000000
2        chr1   3214662   3214663   Xkr4      -  0.199716  0.199716
3        chr1   3214724   3214725   Xkr4      -  0.152102  0.152102
4        chr1   3214732   3214733   Xkr4      -  0.652838  0.652837
...       ...       ...       ...    ...    ...       ...       ...
2365639  chrY  90816052  90816053  Erdr1      +  0.000000  0.001326
2365640  chrY  90816092  90816093  Erdr1      +  0.000000  0.006040
2365641  chrY  90816102  90816103  Erdr1      +  0.000000  0.006445
2365642  chrY  90816142  90816143  Erdr1      +  0.000000  0.036718
2365643  chrY  90816172  90816173  Erdr1      +  0.000000  0.003892

[2365644 rows x 7 columns]

In [11]:
M6A = M6A[["chrom","Start","End","name","strand","Deletion"]]

In [12]:
M6A.columns = ["chrom","m6AStart","m6AEnd","name","strand","Probabilty"]

In [13]:
Data = pd.merge(M6A, Data, how="inner", on=["chrom","name","strand"])

In [14]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,GeneLength
0,chr1,3214485,3214486,Xkr4,-,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
1,chr1,3214554,3214555,Xkr4,-,0.000000,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
2,chr1,3214662,3214663,Xkr4,-,0.199716,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
3,chr1,3214724,3214725,Xkr4,-,0.152102,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
4,chr1,3214732,3214733,Xkr4,-,0.652837,3214481,3671498,3216021,3671348,3,"3214481,3421701,3670551,","3216968,3421901,3671498,",3214481,3216968,457017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280534,chrY,90816052,90816053,Erdr1,+,0.001326,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023
2280535,chrY,90816092,90816093,Erdr1,+,0.006040,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023
2280536,chrY,90816102,90816103,Erdr1,+,0.006445,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023
2280537,chrY,90816142,90816143,Erdr1,+,0.036718,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023
2280538,chrY,90816172,90816173,Erdr1,+,0.003892,90785441,90816464,90785670,90816447,4,"90785441,90793295,90816348,90816435,","90785979,90793417,90816433,90816464,",90816435,90816464,31023

In [15]:
Data = pd.merge(Data, Exon, how="inner", on=["chrom","name","strand"])

In [16]:
Data = Data[(Data["m6AStart"]>=Data["Start"]) & (Data["m6AEnd"]<=Data["End"])]
Data = Data.reset_index(drop = True)

In [17]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,exonEnds,LastExonStart,LastExonEnd,GeneLength,Start,End,ExonOrder,Interval,ExonLength,CumSum
0,chr1,3214485,3214486,Xkr4,-,0.000000,3214481,3671498,3216021,3671348,...,"3216968,3421901,3671498,",3214481,3216968,457017,3214481,3216968,3,1,2487,3634
1,chr1,3214554,3214555,Xkr4,-,0.000000,3214481,3671498,3216021,3671348,...,"3216968,3421901,3671498,",3214481,3216968,457017,3214481,3216968,3,1,2487,3634
2,chr1,3214662,3214663,Xkr4,-,0.199716,3214481,3671498,3216021,3671348,...,"3216968,3421901,3671498,",3214481,3216968,457017,3214481,3216968,3,1,2487,3634
3,chr1,3214724,3214725,Xkr4,-,0.152102,3214481,3671498,3216021,3671348,...,"3216968,3421901,3671498,",3214481,3216968,457017,3214481,3216968,3,1,2487,3634
4,chr1,3214732,3214733,Xkr4,-,0.652837,3214481,3671498,3216021,3671348,...,"3216968,3421901,3671498,",3214481,3216968,457017,3214481,3216968,3,1,2487,3634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,90793403,90793404,Erdr1,+,0.232404,90785441,90816464,90785670,90816447,...,"90785979,90793417,90816433,90816464,",90816435,90816464,31023,90793295,90793417,2,0,122,660
1675586,chrY,90793407,90793408,Erdr1,+,0.218156,90785441,90816464,90785670,90816447,...,"90785979,90793417,90816433,90816464,",90816435,90816464,31023,90793295,90793417,2,0,122,660
1675587,chrY,90816374,90816375,Erdr1,+,0.000000,90785441,90816464,90785670,90816447,...,"90785979,90793417,90816433,90816464,",90816435,90816464,31023,90816348,90816433,3,2,85,745
1675588,chrY,90816408,90816409,Erdr1,+,0.000000,90785441,90816464,90785670,90816447,...,"90785979,90793417,90816433,90816464,",90816435,90816464,31023,90816348,90816433,3,2,85,745
1675589,chrY,90816418,90816419,Erdr1,+,0.000000,90785441,90816464,90785670,90816447,...,"90785979,90793417,90816433,90816464,",90816435,90816464,31023,90816348,90816433,3,2,85,745

In [18]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [19]:
Positive["M6APOS"] = (Positive["m6AStart"]-Positive["Start"]) + (Positive["CumSum"]-Positive["ExonLength"])
Negative["M6APOS"] = (Negative["End"]-Negative["m6AEnd"]) + (Negative["CumSum"]-Negative["ExonLength"])

In [20]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [21]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,LastExonStart,LastExonEnd,GeneLength,Start,End,ExonOrder,Interval,ExonLength,CumSum,M6APOS
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4844962,4846739,38917,4807822,4807982,1,0,160,160,28
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4844962,4846739,38917,4807822,4807982,1,0,160,160,68
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4844962,4846739,38917,4807822,4807982,1,0,160,160,101
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4844962,4846739,38917,4807822,4807982,1,0,160,160,101
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4844962,4846739,38917,4807822,4807982,1,0,160,160,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713423,89713657,32109,89724833,89724900,5,1,67,345,281
1675586,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713423,89713657,32109,89731936,89731971,4,2,35,278,254
1675587,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713423,89713657,32109,89743993,89744125,2,0,132,176,143
1675588,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713423,89713657,32109,89743993,89744125,2,0,132,176,122
1675589,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713423,89713657,32109,89743993,89744125,2,0,132,176,44

In [22]:
Data.drop(["Start","End","ExonOrder","ExonLength","CumSum"], axis=1, inplace=True)

In [23]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,GeneLength,Interval,M6APOS
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,28
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,68
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,1,281
1675586,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,2,254
1675587,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,143
1675588,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,122
1675589,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,44

In [24]:
Data = pd.merge(Data, Exon, how="inner", on=["chrom","name","strand"])

In [25]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,LastExonEnd,GeneLength,Interval_x,M6APOS,Start,End,ExonOrder,Interval_y,ExonLength,CumSum
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4807822,4807982,1,0,160,160
1,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4808454,4808486,2,0,32,192
2,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4828583,4828649,3,2,66,258
3,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4830267,4830315,4,2,48,306
4,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4832310,4832381,5,2,71,377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25624151,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89724233,89724268,6,2,35,380
25624152,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89716975,89717093,7,1,118,498
25624153,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89716123,89716223,8,2,100,598
25624154,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89714015,89714114,9,0,99,697
25624155,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89713423,89713657,10,0,234,931

In [26]:
Data = Data[(Data["Start"]==Data["LastExonStart"]) & (Data["End"]==Data["LastExonEnd"])]

In [27]:
Data = Data.reset_index(drop = True)

In [28]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,LastExonEnd,GeneLength,Interval_x,M6APOS,Start,End,ExonOrder,Interval_y,ExonLength,CumSum
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,28,4844962,4846739,9,0,1777,2507
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,68,4844962,4846739,9,0,1777,2507
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,101,4844962,4846739,9,0,1777,2507
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,101,4844962,4846739,9,0,1777,2507
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,4846739,38917,0,104,4844962,4846739,9,0,1777,2507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,1,281,89713423,89713657,10,0,234,931
1675586,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,2,254,89713423,89713657,10,0,234,931
1675587,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,143,89713423,89713657,10,0,234,931
1675588,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,122,89713423,89713657,10,0,234,931
1675589,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,89713657,32109,0,44,89713423,89713657,10,0,234,931

In [29]:
Data["POS"] = Data["CumSum"] - Data["ExonLength"]

In [30]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,GeneLength,Interval_x,M6APOS,Start,End,ExonOrder,Interval_y,ExonLength,CumSum,POS
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,38917,0,28,4844962,4846739,9,0,1777,2507,730
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,38917,0,68,4844962,4846739,9,0,1777,2507,730
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,38917,0,101,4844962,4846739,9,0,1777,2507,730
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,38917,0,101,4844962,4846739,9,0,1777,2507,730
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,38917,0,104,4844962,4846739,9,0,1777,2507,730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,32109,1,281,89713423,89713657,10,0,234,931,697
1675586,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,32109,2,254,89713423,89713657,10,0,234,931,697
1675587,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,32109,0,143,89713423,89713657,10,0,234,931,697
1675588,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,32109,0,122,89713423,89713657,10,0,234,931,697
1675589,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,32109,0,44,89713423,89713657,10,0,234,931,697

In [31]:
Data.drop(["Start","End","ExonOrder","ExonLength","CumSum"], axis=1, inplace=True)

In [32]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd,GeneLength,Interval_x,M6APOS,Interval_y,POS
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,28,0,730
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,68,0,730
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101,0,730
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101,0,730
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,9,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,104,0,730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675585,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,1,281,0,697
1675586,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,2,254,0,697
1675587,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,143,0,697
1675588,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,122,0,697
1675589,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,10,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,44,0,697

In [33]:
Data["Distance"] = Data["M6APOS"] - Data["POS"]

In [34]:
Data = Data[(Data["Distance"]>= -1000) & (Data["Distance"]<= 1000)]

In [35]:
Data = Data.reset_index(drop = True)

In [36]:
Data

,chrom,m6AStart,m6AEnd,name,strand,Probabilty,txStart,txEnd,cdsStart,cdsEnd,...,exonStarts,exonEnds,LastExonStart,LastExonEnd,GeneLength,Interval_x,M6APOS,Interval_y,POS,Distance
0,chr1,4807850,4807851,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,28,0,730,-702
1,chr1,4807890,4807891,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,68,0,730,-662
2,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101,0,730,-629
3,chr1,4807923,4807924,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,101,0,730,-629
4,chr1,4807926,4807927,Lypla1,+,0.0,4807822,4846739,4807913,4845016,...,"4807822,4808454,4828583,4830267,4832310,483700...","4807982,4808486,4828649,4830315,4832381,483707...",4844962,4846739,38917,0,104,0,730,-626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871760,chrY,89724896,89724897,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,1,281,0,697,-416
871761,chrY,89731959,89731960,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,2,254,0,697,-443
871762,chrY,89744025,89744026,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,143,0,697,-554
871763,chrY,89744046,89744047,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,122,0,697,-575
871764,chrY,89744124,89744125,Gm21996,-,0.0,89713423,89745532,89713627,89744111,...,"89713423,89714015,89716123,89716975,89724233,8...","89713657,89714114,89716223,89717093,89724268,8...",89713423,89713657,32109,0,44,0,697,-653

In [37]:
Data.to_csv("Temp/mm10_M6A.csv", index=0)